################################################################################
# This makefile was produced by Boi Vuong 2012/09/06.
SHELL=	/bin/sh
CMD=	copygb
FOPTS=	-O3 -g -r8 -auto -openmp
LOPTS=  -openmp
INCS=	
OBJS=	copygb.o
#LIBS= -L/nwprod/lib -lw3nco_d -lbacio_4 -lip_d -lsp_d	
LIBS=   ${W3NCO_LIBd} ${BACIO_LIB4} ${IP_LIBd} ${SP_LIBd}
################################################################################
$(CMD):	$(OBJS)
	ifort $(LOPTS) $(OBJS) $(LIBS) -o $(CMD)
$(OBJS):	$(INCS)
copygb.o:	copygb.F
	ifort -c $(FOPTS) $*.F
clean:	
	-rm -f $(OBJS)
