.TH "/home/ed/NCEPLIBS-grib_util/src/tocgrib/tocgrib.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "tocgrib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/tocgrib/tocgrib.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBtocgrib\fP"
.br
.RI "Program reads selected GRIB fields from a file, adds a TOC Flag Field separator block and WMO Header in front of each GRIB field, and writes them out to a new file\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
GILBERT 
.RE
.PP
\fBDate\fP
.RS 4
2003-03-28 
.RE
.PP

.PP
Definition in file \fBtocgrib\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program tocgrib"

.PP
Program reads selected GRIB fields from a file, adds a TOC Flag Field separator block and WMO Header in front of each GRIB field, and writes them out to a new file\&. The output file is in the format required for TOC's FTP Input Service, which can be used to disseminate the GRIB bulletins\&. This service is described at http://weather.gov/tg/ftpingest.html\&.
.PP
PROGRAM HISTORY LOG: -2003-03-28 Gilbert -2012-10-22 VUONG CHANGED VARIABLE ENVVAR TO CHARACTER*6 -2016-10-15 VUONG Increased length of file name to 200 Characters
.PP
USAGE: INPUT FILES:
.IP "\(bu" 2
5 - LIST OF GRIB FIELDS AND ASSOCIATED WMO HEADERS\&.
.IP "\(bu" 2
11 - INPUT GRIB FILE\&.
.IP "\(bu" 2
31 - CORRESPONDING INPUT GRIB INDEX FILE\&.
.IP "\(bu" 2
PARM - PASS IN 4 CHARACTERS 'KWBX' WITH PARM FIELD
.PP
OUTPUT FILES: (INCLUDING SCRATCH FILES)
.IP "\(bu" 2
6 - STANDARD FORTRAN PRINT FILE
.IP "\(bu" 2
51 - OUTPUT GRIB BULLETIN FILE IN TOC FORMAT
.PP
SUBPROGRAMS CALLED: (LIST ALL CALLED FROM ANYWHERE IN CODES)
.IP "\(bu" 2
UNIQUE: - MAKWMO LIBRARY:
.IP "\(bu" 2
W3LIB - W3TAGB W3UTCDAT IW3PDS W3FP11 W3TAGE W3AS00 GETGBP
.IP "\(bu" 2
BACIO - BAREAD BAOPENR BAOPENW BACLOSE
.PP
EXIT STATES:
.IP "  \(bu" 4
COND = 0 - SUCCESSFUL RUN
.IP "  \(bu" 4
10 - Error opening input GRIB data file
.IP "  \(bu" 4
20 - Error opening output GRIB transmission file
.IP "  \(bu" 4
19 - ERROR READING CONTROL CARD FILE - All Bulletins missing
.IP "  \(bu" 4
30 - Some BULLETINS ARE MISSING 
.PP

.PP

.PP
Definition at line 41 of file tocgrib\&.f\&.
.PP
References makwmo(), and mkfldsep()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for tocgrib from the source code\&.
