.TH "/home/ed/NCEPLIBS-grib_util/src/tocgrib/mkfldsep.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "tocgrib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/tocgrib/mkfldsep.f \- Makes TOC Flag Field Separator Block\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBmkfldsep\fP (csep, iopt, lenin, lenbull, lenout)"
.br
.RI "Generates a TOC Flag Field Separator Block used to separate WMO Bulletins within a transmission file to be ingested in TOC's FTP Input Service, which can be used to disseminate WMO buletins\&. "
.in -1c
.SH "Detailed Description"
.PP 
Makes TOC Flag Field Separator Block\&. 


.PP
\fBAuthor\fP
.RS 4
Gilbert 
.RE
.PP
\fBDate\fP
.RS 4
2002-09-16 
.RE
.PP

.PP
Definition in file \fBmkfldsep\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine mkfldsep (character*(*), intent(out) csep, integer, intent(in) iopt, integer, intent(in) lenin, integer, intent(in) lenbull, integer, intent(out) lenout)"

.PP
Generates a TOC Flag Field Separator Block used to separate WMO Bulletins within a transmission file to be ingested in TOC's FTP Input Service, which can be used to disseminate WMO buletins\&. 
.br
 ( see http://weather.gov/tg/ftpingest.html )
.PP
This routine can generate different flag field separator blocks depending on the value of variable iopt\&.
.PP
Bulletin 'Flag Field Separator' block - OPTION 1 (old) bytes 1 - 4 marker string (####) 5 - 7 block length [018 fixed value] 8 - 13 total length of bulletin in bytes [octets] (not including the flag field block) 14 - 17 marker string (####) 18 line Feed (ASCII '0A')
.PP
Bulletin 'Flag Field Separator' block - OPTION 1a (new) bytes 1 - 4 marker string (####) 5 - 7 block length (nnn) - value always greater than 018 8 - 18 total length of bulletin in bytes [octets] (not including the flag field block) 19 - nnn-5 reserved for future use nnn-4 - nnn-1 marker string (####) nnn line Feed (ASCII '0A')
.PP
Bulletin 'Flag Field Separator' block - OPTION 2 (limited) bytes 1 - 4 marker string (****) 5 - 14 total length of bulletin in bytes [octets] (not including the flag field block) 15 - 18 marker string (****) 19 line Feed (ASCII '0A')
.PP
PROGRAM HISTORY LOG: 2002-09-16 Gilbert ORIGINAL AUTHOR
.PP
USAGE: call mkfldsep(csep,iopt,lenin,lenbull,lenout) 
.PP
\fBParameters\fP
.RS 4
\fIcsep*(*)\fP Character array containing the flag field separator\&. 
.br
\fIiopt\fP Flag Field Separator block option: = 1: Separator block for use with alphanumeric bulletins\&. if lenin <= 18 and lenbull <= 999999, OPTION 1 block will be generated\&. if lenin > 18 or lenbull > 999999, OPTION 1a block will be generated\&. = 2: Separator block for use with GRIB/BUFR bulletins\&. 
.br
\fIlenin\fP Desired length of the flag field separator block\&. ignored, if iopt=2\&. 
.br
\fIlenbull\fP Integer length of the bulletin (in bytes) that will follow this separator block\&. 
.br
\fIlenout\fP Integer length of the flag field separator block\&. 
.RE
.PP

.PP
Definition at line 56 of file mkfldsep\&.f\&.
.PP
Referenced by tocgrib()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for tocgrib from the source code\&.
