.TH "/home/ed/NCEPLIBS-grib_util/src/tocgrib/tocgrib.F90" 3 "Fri Mar 22 2024" "Version 1.4.0" "tocgrib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/tocgrib/tocgrib.F90 \- Create new GRIB2 file from exiting GRIB2 file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBtocgrib\fP"
.br
.RI "Create new GRIB2 file from exiting GRIB2 file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Create new GRIB2 file from exiting GRIB2 file\&. 


.PP
\fBAuthor\fP
.RS 4
Gilbert 
.RE
.PP
\fBDate\fP
.RS 4
2003-03-28 
.RE
.PP

.PP
Definition in file \fBtocgrib\&.F90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program tocgrib"

.PP
Create new GRIB2 file from exiting GRIB2 file\&. This program reads selected GRIB2 fields from a file, adds a TOC Flag Field separator block and WMO Header in front of each GRIB2 field, and writes them out to a new file\&. The output file is in the format required for TOC's FTP Input Service, which can be used to disseminate the GRIB bulletins\&. This service is described at http://weather.gov/tg/ftpingest.html\&.
.SS "Input Files"
.IP "\(bu" 2
5 list of grib fields and associated wmo headers\&.
.IP "\(bu" 2
11 input grib file\&.
.IP "\(bu" 2
31 corresponding input grib index file\&.
.IP "\(bu" 2
parm pass in 4 characters 'kwbx' with parm field
.PP
.SS "Output Files (Including Scratch Files)"
.IP "\(bu" 2
6 standard fortran print file
.IP "\(bu" 2
51 output grib bulletin file in toc format
.PP
.PP
\fBReturns\fP
.RS 4
.IP "\(bu" 2
0 Successful run
.IP "\(bu" 2
10 Error opening input GRIB data file
.IP "\(bu" 2
20 Error opening output GRIB transmission file
.IP "\(bu" 2
19 Error reading control card file - all bulletins missing
.IP "\(bu" 2
30 Some BULLETINS ARE MISSING
.PP
.RE
.PP
\fBAuthor\fP
.RS 4
Gilbert 
.RE
.PP
\fBDate\fP
.RS 4
2003-03-28 
.RE
.PP

.PP
Definition at line 32 of file tocgrib\&.F90\&.
.PP
References makwmo(), and mkfldsep()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for tocgrib from the source code\&.
