.TH "/home/ed/NCEPLIBS-grib_util/src/tocgrib2/tocgrib2.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "tocgrib2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/tocgrib2/tocgrib2.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBtocgrib2\fP"
.br
.RI "Program reads selected GRIB2 fields from a file, adds a TOC Flag Field separator block and WMO Header in front of each GRIB2 field, and writes them out to a new file\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
GILBERT 
.RE
.PP
\fBDate\fP
.RS 4
2004-05-17 
.RE
.PP

.PP
Definition in file \fBtocgrib2\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program tocgrib2"

.PP
Program reads selected GRIB2 fields from a file, adds a TOC Flag Field separator block and WMO Header in front of each GRIB2 field, and writes them out to a new file\&. The output file is in the format required for TOC's FTP Input Service, which can be used to disseminate the GRIB2 bulletins\&. This service is described at http://weather.gov/tg/ftpingest.html\&.
.PP
PROGRAM HISTORY LOG:
.IP "\(bu" 2
2004-05-17 Gilbert
.IP "\(bu" 2
2012-06-14 VUONG Modified write statement with format specifier
.IP "\(bu" 2
2012-10-22 VUONG CHANGED VARIABLE ENVVAR TO CHARACTER*6
.IP "\(bu" 2
2016-10-15 VUONG Increased length of file name to 200 Characters
.PP
.PP
USAGE: INPUT FILES:
.IP "\(bu" 2
5 - NAMELIST OF GRIB FIELDS AND ASSOCIATED WMO HEADERS\&.
.IP "\(bu" 2
11 - INPUT GRIB2 FILE\&.
.IP "\(bu" 2
31 - CORRESPONDING INPUT GRIB2 INDEX FILE\&.
.PP
.PP
OUTPUT FILES: (INCLUDING SCRATCH FILES)
.IP "\(bu" 2
6 - STANDARD FORTRAN PRINT FILE
.IP "\(bu" 2
51 - OUTPUT GRIB BULLETIN FILE IN TOC FORMAT
.PP
.PP
SUBPROGRAMS CALLED: (LIST ALL CALLED FROM ANYWHERE IN CODES) UNIQUE: - MAKWMO LIBRARY:
.IP "\(bu" 2
W3LIB - W3TAGB W3TAGE mkfldsep makwmo
.IP "\(bu" 2
G2LIB - GETGB2P
.IP "\(bu" 2
BACIO - BAREAD BAOPENR BAOPENW BACLOSE WRYTE
.PP
.PP
EXIT STATES:
.IP "\(bu" 2
COND = 0 - SUCCESSFUL RUN
.IP "\(bu" 2
10 - Error opening input GRIB2 data file
.IP "\(bu" 2
20 - Error opening output GRIB transmission file
.IP "\(bu" 2
19 - ERROR READING CONTROL CARD FILE - All Bulletins missing
.IP "\(bu" 2
30 - Some BULLETINS ARE MISSING
.PP
.PP
REMARKS: The 'EXTRACT' variable in the namelist allows users to choose whether they want the entire GRIB2 message containing the requested field (extract=\&.false\&.), OR a GRIB2 message containing only the requested field (extract=\&.true\&.)\&. Both options return the same message if the requested field is the only field in the GRIB2 message\&. 
.PP
Definition at line 48 of file tocgrib2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for tocgrib2 from the source code\&.
