################################################################################
# This makefile was produced by fmjif at 17:21:11 on 97/02/24.
SHELL=	/bin/sh
CMD=	grb2index
FOPTS= -O3 -g -convert big_endian
LOPTS=	
INCS=	
OBJS=	grb2index.o
#LIBS=	-L/nwprod/lib -lg2_4 -lw3nco_4 -lbacio_4
LIBS=   ${G2_LIB4} ${W3NCO_LIB4} ${BACIO_LIB4}
################################################################################
$(CMD):	$(OBJS)
	ifort $(LOPTS) $(OBJS) $(LIBS) -o $(CMD)
$(OBJS):	makefile $(INCS)
grb2index.o:	grb2index.f
	ifort -c $(FOPTS) $*.f
clean:	
	-rm -f $(OBJS)
