/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnv12.F90
NAME
/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnv12.F90 - Convert every GRIB1 field in a file to a GRIB2 field.
SYNOPSIS
Functions/Subroutines
subroutine cnv12 (ifl1, ifl2, ipack, usemiss, imiss, uvvect, table_ver)
This subroutine converts every GRIB1 field in a file to a GRIB2 field.
Detailed Description
Convert every GRIB1 field in a file to a GRIB2 field.
Author
Stephen Gilbert
Date
2003-06-11
Definition in file cnv12.F90.
Function/Subroutine Documentation
subroutine cnv12 (integer, intent(in) ifl1, integer, intent(in) ifl2, integer, intent(in) ipack, logical, intent(in) usemiss, integer imiss, logical, intent(in) uvvect, integer table_ver)
This subroutine converts every GRIB1 field in a file to a GRIB2 field. U and V wind component fields are combined into a single GRIB2 message.
Program History Log
Date Programmer Comments 2003-06-11 Gilbert Initial 2003-05-19 Gilbert Changed Master Table Version Number from 1 to 2. Added check for grib1 table version with params 191 and 192 for ensemble probs. 2007-03-26 Gordon Added check for ECMWF data to reference ECMWF Conversion tables. 2007-10-11 Vuong Added check for ensemble probs if the kpds > 28 2008-01-28 Vuong Fixed the V-GRD BY SETTING THE LPDS(22) = -1 and increase the array size MAXPTS 2008-05-14 Vuong Add option -m0 No explicit missing values included within data values 2010-12-02 Vuong Changed Master Table Version Number from 2 to 6. - Add option -mastertable_ver_x where x is mater table version 2 to 10 2011-07-22 Vuong Changed variable kprob(1) to kpds(5) in calling routine param_g1_to_g2 2012-03-21 Vuong Set the Shape of Earth to 2 (oblate spheroid earth) for IMSSNOW (Polar Stereo graphic) Grid.
Parameters
ifl1 Fortran unit number of input GRIB1 file.
ifl2 Fortran unit number of output GRIB2 file.
ipack GRIB2 packing option: value option 0 simple packing 2 group packing 31 group pack with 1st order differencing 32 group pack with 2nd order differencing 40 JPEG2000 encoding 40000 JPEG2000 encoding (obsolete) 41 PNG encoding 40010 PNG encoding (obsolete) If ipack .ne. one of the values above, 31 is used as a default.
usemiss uses missing value management (instead of bitmaps), for use ipack options 2, 31, and 32.
imiss Missing value management:
0 No explicit missing values included within data values
1 Primary missing values included within data values
uvvect U/V vector control:
.true. combine U and V wind components into one GRIB2 msg.
.flase. does not combine U and V wind components
table_ver Master Table version where x is number from 2 to 10.
Author
Stephen Gilbert
Date
2003-06-11
Definition at line 47 of file cnv12.F90.
References gds2gdt(), pds2pdt(), and pds2pdtens().
Referenced by cnvgrib().
Author
Generated automatically by Doxygen for cnvgrib from the source code.