/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnv21.F90
NAME
/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnv21.F90 - Convert every GRIB2 field to individual GRIB1 messages.
SYNOPSIS
Functions/Subroutines
subroutine cnv21 (ifl1, ifl2)
This subroutine converts every GRIB2 field in a file to a GRIB1 field.
Detailed Description
Convert every GRIB2 field to individual GRIB1 messages.
Author
Stephen Gilbert
Date
2003-06-11
Definition in file cnv21.F90.
Function/Subroutine Documentation
subroutine cnv21 (integer, intent(in) ifl1, integer, intent(in) ifl2)
This subroutine converts every GRIB2 field in a file to a GRIB1 field. If a GRIB2 message contains more than one data field, then each field is saved in individual GRIB1 messages.
Program History Log
Date Programmer Comments 2003-06-11 Gilbert Initial 2008-05-14 Vuong Add option -m0 No explicit missing values included within data values.
Parameters
ifl1 Fortran unit number of input GRIB2 file.
ifl2 Fortran unit number of output GRIB1 file.
Author
Stephen Gilbert
Date
2003-06-11
Definition at line 19 of file cnv21.F90.
References gdt2gds(), makepds(), makepdsens(), and putgbexn().
Referenced by cnvgrib().
Author
Generated automatically by Doxygen for cnvgrib from the source code.