/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnvgrib.F90
NAME
/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnvgrib.F90 - Convert files between GRIB1 and GRIB2.
SYNOPSIS
Functions/Subroutines
program cnvgrib
This program converts every GRIB field in a file between GRIB1 and GRIB2.
subroutine usage (iopt)
This routine prints a brief description of the command line options.
Detailed Description
Convert files between GRIB1 and GRIB2.
Author
Stephen Gilbert
Date
2003-06-06
Definition in file cnvgrib.F90.
Function/Subroutine Documentation
program cnvgrib
This program converts every GRIB field in a file between GRIB1 and GRIB2. The following conversions are supported:
1.
GRIB1 to GRIB2
2.
GRIB2 to GRIB1
3.
GRIB2 to GRIB2.
Program History Log
Date Programmer Comments 2003-06-06 Gilbert Initial 2008-05-14 Vuong Added the option -m0 (No explicit missing values included within the datavalues, modified the options and help messages 2010-12-02 Vuong Changed Master Table Version Number from 2 to 6. Add option -mastertable_ver_x where x is mater table version 2 to 10 2012-03-29 Vuong Changed Master Table Version Number from 2 to 8. 2013-07-24 Vuong Changed Master Table Version Number from 2 to 11 2016-09-30 Vuong Modified to correct forecast hour beyon F252 when convert from grib2 to grib1. Fixed memory leak and complex packing 2018-07-26 Vuong Checked Time Range for continuous accumulated APCP after F252 when convert from grib2 to grib1
Returns
0 Success.
2 Problem processing command line arguments.
3 Problem opening input GRIB file.
4 Problem opening output GRIB file.
5 Unknown conversion option.
Author
Stephen Gilbert
Date
2003-06-06
Definition at line 32 of file cnvgrib.F90.
References cnv12(), cnv21(), cnv22(), and usage().
subroutine usage (integer, intent(in) iopt)
This routine prints a brief description of the command line options.
Parameters
iopt ouput option: 1 = print description of arguments, otherwise, print command usage summary.
Author
Stephen Gilbert
Date
2003-06-06
Definition at line 264 of file cnvgrib.F90.
Referenced by cnvgrib().
Author
Generated automatically by Doxygen for cnvgrib from the source code.