.TH "/home/ed/NCEPLIBS-grib_util/src/grib2grib/grib2grib.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "grib2grib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/grib2grib/grib2grib.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBgrib2grib\fP"
.br
.RI "FINDS AND EXTRACTS GRIB RECORDS FROM A GRIB FILE MADE BY GRIBAWP1 FOR FAMILY OF SERVICES\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
VUONG 
.RE
.PP
\fBDate\fP
.RS 4
2001-05-18 
.RE
.PP

.PP
Definition in file \fBgrib2grib\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program grib2grib"

.PP
FINDS AND EXTRACTS GRIB RECORDS FROM A GRIB FILE MADE BY GRIBAWP1 FOR FAMILY OF SERVICES\&. CONTROL CARDS CAN BE USED TO READ AND EXTRACT ALL OR SELECTED GRIB RECORDS FROM A GRIB FILE\&. TO EXTRACT ONLY A SELECTED NUMBER OF GRIB RECORDS FROM A GRIB FILE, A CONTROL CARD WITH A PDS CAN BE USED\&. IF THE PDS IN THE CONTROL CARD IS FOUND IN THE INPUT GRIB FILE, THE ENTIRE GRIB MESSAGE 'GRIB' TO '7777' IS WRITTEN TO THE DESIGNATED OUTPUT FILE\&. CONTROL CARDS CAN ALSO BE USED TO EXTRACT GRIB RECORDS ACCORDING TO THEIR GRID TYPE\&. NOTE: THIS PROGRAM WAS DERIVED FROM THE 'unpkgrb1\&.f' CODE BUT DOES NOT UNPACK ANY DATA\&.
.PP
PROGRAM HISTORY LOG:
.IP "\(bu" 2
96-05-21 SOUTHALL
.IP "\(bu" 2
98-05-07 JOHNSON
.IP "\(bu" 2
98-07-01 VUONG CONVERTED TO FORTRAN 90 AND Y2K COMPLIANT REMOVED CALLS TO W3LOG
.IP "\(bu" 2
99-05-19 VUONG CONVERTED TO IBM RS/6000 SP
.IP "\(bu" 2
01-05-18 VUONG INCREASING THE SIZE OF WORK ARRAY TO HANDLE THE LARGER GRIB FILE\&.
.IP "\(bu" 2
2012-08-09 VUONG MODIFIED TO USE MODULE IFPORT
.PP
.PP
USAGE: INPUT FILES:
.IP "\(bu" 2
5 - INPUT CONTROL CARDS (3 TYPES) FORMAT (I1,I3,A44) FORMAT (A44) FORMAT (6(2X,4Z2),2X,I1)
.IP "\(bu" 2
11 - INTERNAL UNIT NUMBER OF AWIP GRIB INPUT FILE
.PP
.PP
OUTPUT FILES:
.IP "\(bu" 2
6 - PRINT OUTPUT (STANDARD OUTPUT - FORTRAN) PRINTS ON SCREEN OF PC/WORKSTATION\&.
.IP "\(bu" 2
51 - 1 WRITE FOR EACH GRIB RECORD ENTIRE GRIB MESSAGE, 'GRIB' TO '7777'
.PP
.PP
SUBPROGRAMS CALLED:
.IP "\(bu" 2
W3LIB - IW3PDS, XMOVEX, W3TAGB
.PP
.PP
EXIT STATES:
.IP "\(bu" 2
COND = 0 SUCCESSFUL RUN
.IP "\(bu" 2
= 10 ERROR ON OPEN OF CONTROL CARD FILE
.IP "\(bu" 2
= 20 ERROR ON OPEN OF INPUT GRIB FILE
.IP "\(bu" 2
= 30 ERROR ON OPEN OF OUTPUT PACKED GRIB FILE
.IP "\(bu" 2
= 40 ERROR, INPUT GRIB FILE IS TOO BIG, CHANGE PROGRAM
.IP "\(bu" 2
= 60 ERROR READING GRIB FILE
.IP "\(bu" 2
= 99 I/O ERROR USING STAT FUNCTION
.IP "\(bu" 2
= 100 PROGRAMMER FORGOT CONTROL CARDS
.IP "\(bu" 2
= 110 NO CARD WITH FFFFFFFF SHOWING END OF PDS CARDS
.PP
.PP
WARNING: On a CRAY you may have to use assign cards\&. If your job prints the file name and file byte size O\&.K\&. but quits with an OPEN INPUT FILE ERROR, use these assign cards (at the prompt)\&.
.PP
$ assign -R $ assign -a input-file-name -s sbin input-file-name
.PP
EXAMPLE: CONTROL CARDS IN 'grib2grib\&.dat' FILE
.PP
Example 1\&. To extract selected records (w/out unpacking them) from file xtrn\&.eta24 and xtrn\&.mrf144 using cards read in with the PDS of the record\&. After the last card with a PDS, the next card must have FFFFFFFF starting in column 3\&. Get the 500 mb HGT and 500 mb TMP (1st 2 PDS's) and the 850 mb RH and the MSL (2nd 2 PDS's) and write the packed data into eta\&.packed\&.dat and mso\&.packed\&.dat respectively\&. The PDS's of these fields and other can be obtained by getting an inventory of the input grib files xtrn\&.eta24 and xtrn\&.mso30\&. Column 63 is set to 2 so that only 11 of the 1st 12 bytes are used to find records\&. For more info\&. concerning the number in Col\&. 63 refer to the subroutine 'iw3pds\&.f'
.PP
.PP
.nf
      
  col\&. 1
       0000xtrn\&.eta24
       eta\&.packed\&.dat
         00001C02  0759D380  076401F4  00000000  00000000  00000000  2
         00001C02  0759D380  0B6401F4  00000000  00000000  00000000  2
         FFFFFFFF  00000000  00000000  00000000  00000000  00000000  0
       0000xtrn\&.mso30
       mso\&.packed\&.dat
         00001C02  0755D4C0  34640352  00000000  00000000  00000000  2
         00001C02  074EC980  02660000  00000000  00000000  00000000  2
         FFFFFFFF  00000000  00000000  00000000  00000000  00000000  0
 
.fi
.PP
 
.br
.PP
Example 2\&. To extract only the grib messages from xtrn\&.mrf144 and write them (without unpacking) into mrf\&.packed\&.dat\&.
.PP
.PP
.nf
      
  col\&. 1
       1000xtrn\&.mrf144
       mrf\&.packed\&.dat
 
.fi
.PP
 
.br
.PP
Example 3\&. To extract all grib records in the file xtrn\&.mrf144 by grid type 201 and 203 placing them into mrf201\&.dat and mrf203\&.dat respectively\&. 
.PP
.nf
      
  col\&. 1
       2201xtrn\&.mrf144
       mrf201\&.dat
       2203xtrn\&.mrf144
       mrf203\&.dat
 
.fi
.PP
 
.br
 
.PP
Definition at line 112 of file grib2grib\&.f\&.
.PP
References hexchar()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grib2grib from the source code\&.
