.TH "/home/ed/NCEPLIBS-grib_util/src/degrib2/degrib2.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "degrib2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/degrib2/degrib2.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBdegrib2\fP"
.br
.RI "This program reads GRIB2 file and makes inventory of GRIB file\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Vuong 
.RE
.PP
\fBDate\fP
.RS 4
2010-09-08 
.RE
.PP

.PP
Definition in file \fBdegrib2\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program degrib2"

.PP
This program reads GRIB2 file and makes inventory of GRIB file\&. PROGRAM HISTORY LOG:
.IP "\(bu" 2
2010-09-06 Vuong
.IP "\(bu" 2
2011-10-03 Vuong Added to check for reference time for PDT 4\&.15
.IP "\(bu" 2
2012-06-07 Vuong Changed PRINT statement to WRITE with format specifier
.IP "\(bu" 2
2017-01-21 Vuong Added to check for undefine values
.PP
.PP
USAGE:
.IP "\(bu" 2
INPUT FILES: UNIT 10 - Input GRIB file
.IP "\(bu" 2
OUTPUT FILES: UNIT 50 - Output GRIB file
.PP
.PP
COMMAND LINE: degrib2 grib2_file
.IP "\(bu" 2
OUTPUT FILES: (INCLUDING SCRATCH FILES) 6 - STANDARD FORTRAN PRINT FILE
.PP
SUBPROGRAMS CALLED: (LIST ALL CALLED FROM ANYWHERE IN CODES)
.IP "  \(bu" 4
G2LIB - GB_INFO, GT_GETFLD, PRLEVEL, PRVTIME
.IP "  \(bu" 4
W3LIB - GBYTE, SKGB
.IP "  \(bu" 4
BACIO - BAOPENR, BAREAD, BACLOSE
.IP "  \(bu" 4
SYSTEM - IARGC FUNCTION RETURNS NUMBER OF ARGUMENT ON COMMAND LINE
.IP "  \(bu" 4
GETARG ROUTINE RETURNS COMMAND LINE ARGUMENT
.PP
.PP
EXIT STATES: COND = 0 - SUCCESSFUL RUN
.PP
.PP
REMARKS: COMMAND LINE CAN HAVE ONE FILE NAME\&. 
.PP
Definition at line 38 of file degrib2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for degrib2 from the source code\&.
