/home/ed/NCEPLIBS-grib_util/src/degrib2/prlevel.F90
NAME
/home/ed/NCEPLIBS-grib_util/src/degrib2/prlevel.F90 - Print level information to a character array, given the GRIB2 Product Definition Template information.
SYNOPSIS
Functions/Subroutines
subroutine frmt (cval, ival, iscal)
Format the level description.
subroutine prlevel (ipdtn, ipdtmpl, labbrev)
Print level information to a character array, given the GRIB2 Product Definition Template information.
Detailed Description
Print level information to a character array, given the GRIB2 Product Definition Template information.
Author
Stephen Gilbert
Date
2010-09-08
Definition in file prlevel.F90.
Function/Subroutine Documentation
subroutine frmt (character(len = 10), intent(out) cval, integer, intent(in) ival, integer, intent(in) iscal)
Format the level description.
Parameters
cval char array that gets the level description.
ival value to be used in level description.
iscal scaling factor (if any) for ival.
Author
Vuong
Date
2010-09-08
Definition at line 258 of file prlevel.F90.
Referenced by prlevel().
subroutine prlevel (integer, intent(in) ipdtn, integer, dimension(*), intent(in) ipdtmpl, character(len = 40), intent(out) labbrev)
Print level information to a character array, given the GRIB2 Product Definition Template information. This subroutine finds the 'Type of first fixed surface' (see [Code table 4.5](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-0.shtml)) using the product definition template value. The location in the template array varies depending on the template number.
Parameters
ipdtn Product Definition Template Number (Code Table 4.0).
ipdtmpl Array of data values for the Product Definition Template specified by ipdtn.
labbrev Character array which gets the string describing the level. Must be of length 40.
Author
Stephen Gilbert
Date
2010-09-08
Definition at line 24 of file prlevel.F90.
References frmt().
Referenced by degrib2().
Author
Generated automatically by Doxygen for degrib2 from the source code.