.TH "/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnv12.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "cnvgrib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnv12.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBcnv12\fP (ifl1, ifl2, ipack, usemiss, imiss, uvvect, table_ver)"
.br
.RI "This subroutine converts every GRIB1 field in a file to a GRIB2 field\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Gilbert 
.RE
.PP
\fBDate\fP
.RS 4
2003-06-11 
.RE
.PP

.PP
Definition in file \fBcnv12\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine cnv12 (integer, intent(in) ifl1, integer, intent(in) ifl2, integer, intent(in) ipack, logical, intent(in) usemiss, integer imiss, logical, intent(in) uvvect, integer table_ver)"

.PP
This subroutine converts every GRIB1 field in a file to a GRIB2 field\&. U and V wind component fields are combined into a single GRIB2 message\&.
.PP
PROGRAM HISTORY LOG:
.IP "\(bu" 2
2003-06-11 Gilbert
.IP "\(bu" 2
2003-05-19 Gilbert - Changed Master Table Version Number from 1 to 2\&.
.IP "  \(bu" 4
Added check for grib1 table version with params 191 and 192 for ensemble probs\&.
.PP

.IP "\(bu" 2
2007-03-26 Gordon - Added check for ECMWF data to reference ECMWF Conversion tables\&.
.IP "\(bu" 2
2007-10-11 Vuong - Added check for ensemble probs if the kpds > 28
.IP "\(bu" 2
2008-01-28 Vuong - Fixed the V-GRD BY SETTING THE LPDS(22)=-1 and increase the array size MAXPTS
.IP "\(bu" 2
2008-05-14 Vuong - Add option -m0 No explicit missing values included within data values
.IP "\(bu" 2
2010-12-02 Vuong - Changed Master Table Version Number from 2 to 6\&.
.IP "  \(bu" 4
Add option -mastertable_ver_x where x is mater table version 2 to 10
.PP

.IP "\(bu" 2
2011-07-22 Vuong - Changed variable kprob(1) to kpds(5) in calling routine param_g1_to_g2
.IP "\(bu" 2
2012-03-21 Vuong - Set the Shape of Earth to 2 (oblate spheroid earth) for IMSSNOW (Polar Stereo graphic) Grid\&.
.PP
.PP
\fBParameters\fP
.RS 4
\fIifl1\fP - Fortran unit number of input GRIB1 file 
.br
\fIifl2\fP - Fortran unit number of output GRIB2 file 
.br
\fIipack\fP - GRIB2 packing option: value   option    0   simple packing    2   group packing    31   group pack with 1st order differencing    32   group pack with 2nd order differencing    40   JPEG2000 encoding    40000   JPEG2000 encoding (obsolete)    41   PNG encoding    40010   PNG encoding (obsolete)   if ipack \&.ne\&. one of the values above, 31 is used as a default\&. 
.br
\fIusemiss\fP - uses missing value management (instead of bitmaps), for use ipack options 2, 31, and 32\&. 
.br
\fIimiss\fP - Missing value management: 0 = No explicit missing values included within data values 1 = Primary missing values included within data values 
.br
\fIuvvect\fP - \&.true\&. = combine U and V wind components into one GRIB2 msg\&. \&.flase\&. = does not combine U and V wind components 
.br
\fItable_ver\fP - Master Table version where x is number from 2 to 10
.RE
.PP
INPUT FILES: See ifl1
.PP
OUTPUT FILES: See ifl2 
.PP
Definition at line 54 of file cnv12\&.f\&.
.PP
References gds2gdt(), pds2pdt(), and pds2pdtens()\&.
.PP
Referenced by cnvgrib()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cnvgrib from the source code\&.
