.TH "/home/ed/NCEPLIBS-grib_util/src/cnvgrib/gds2gdt.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "cnvgrib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/cnvgrib/gds2gdt.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBgds2gdt\fP (kgds, igds, igdstmpl, idefnum, ideflist, iret)"
.br
.RI "This routine converts a GRIB1 GDS ( in format specfied in w3fi63\&.f) to necessary info for a GRIB2 Grid Definition Section\&. "
.in -1c
.SH "Detailed Description"
.PP 


\&. \&. \&. 
.PP
\fBAuthor\fP
.RS 4
Gilbert 
.RE
.PP
\fBDate\fP
.RS 4
2003-06-17 
.RE
.PP

.PP
Definition in file \fBgds2gdt\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine gds2gdt (integer, dimension(*), intent(in) kgds, integer, dimension(*), intent(out) igds, integer, dimension(*), intent(out) igdstmpl, integer, intent(out) idefnum, integer, dimension(*), intent(out) ideflist, integer, intent(out) iret)"

.PP
This routine converts a GRIB1 GDS ( in format specfied in w3fi63\&.f) to necessary info for a GRIB2 Grid Definition Section\&. PROGRAM HISTORY LOG: 2003-06-17 Gilbert 2004-04-27 Gilbert - Added support for Gaussian grids\&. 2007-04-16 Vuong - Added Curvilinear Orthogonal grids\&. 2007-05-29 Vuong - Added Rotate Lat/Lon E-grid (203) 2010-05-10 Vuong - Added Rotate Lat/Lon for Non-E Stagger grid (205) 2011-05-04 Vuong - Corrected Arakawa Lat/Lon of grid points for Non-E Stagger grid (205)
.PP
USAGE: CALL gds2gdt(kgds,igds,igdstmpl,idefnum,ideflist,iret) INPUT ARGUMENT LIST: kgds() - GRIB1 GDS info as returned by w3fi63\&.f
.PP
OUTPUT ARGUMENT LIST: (INCLUDING WORK ARRAYS) igds() - Contains information read from the appropriate GRIB Grid Definition Section 3 for the field being returned\&. Must be dimensioned >= 5\&. igds(1)=Source of grid definition (see Code Table 3\&.0) igds(2)=Number of grid points in the defined grid\&. igds(3)=Number of octets needed for each additional grid points definition\&. Used to define number of points in each row ( or column ) for non-regular grids\&. = 0, if using regular grid\&. igds(4)=Interpretation of list for optional points definition\&. (Code Table 3\&.11) igds(5)=Grid Definition Template Number (Code Table 3\&.1) igdstmpl() - Grid Definition Template values for GDT 3\&.igds(5) idefnum - The number of entries in array ideflist\&. 
.br
 i\&.e\&. number of rows ( or columns ) for which optional grid points are defined\&. ideflist() - Optional integer array containing the number of grid points contained in each row (or column)\&. iret - Error return value: 0 = Successful 1 = Unrecognized GRIB1 grid data representation type
.PP
REMARKS: LIST CAVEATS, OTHER HELPFUL HINTS OR INFORMATION
.PP
ATTRIBUTES: LANGUAGE: INDICATE EXTENSIONS, COMPILER OPTIONS MACHINE: IBM SP 
.PP
Definition at line 52 of file gds2gdt\&.f\&.
.PP
Referenced by cnv12()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cnvgrib from the source code\&.
