.TH "/home/ed/NCEPLIBS-grib_util/src/cnvgrib/setbit.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "cnvgrib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/cnvgrib/setbit.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBsetbit\fP (IBM, IBS, IDS, LEN, MG, G, GMIN, GMAX, NBIT)"
.br
.RI "THE NUMBER OF BITS REQUIRED TO PACK A GIVEN FIELD FOR PARTICULAR BINARY AND DECIMAL SCALINGS IS COMPUTED\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
IREDELL 
.RE
.PP
\fBDate\fP
.RS 4
92-10-31 
.RE
.PP

.PP
Definition in file \fBsetbit\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine setbit ( IBM,  IBS,  IDS,  LEN, dimension(len) MG, dimension(len) G,  GMIN,  GMAX,  NBIT)"

.PP
THE NUMBER OF BITS REQUIRED TO PACK A GIVEN FIELD FOR PARTICULAR BINARY AND DECIMAL SCALINGS IS COMPUTED\&. THE MINIMUM AND MAXIMUM ROUNDED FIELD VALUES ARE ALSO RETURNED\&. GRIB BITMAP MASKING FOR VALID DATA IS OPTIONALLY USED\&.
.PP
PROGRAM HISTORY LOG: 96-09-16 IREDELL
.PP
USAGE: CALL SETBIT(IBM,IBS,IDS,LEN,MG,G,GMIN,GMAX,NBIT) INPUT ARGUMENT LIST: IBM - INTEGER BITMAP FLAG (=0 FOR NO BITMAP) IBS - INTEGER BINARY SCALING (E\&.G\&. IBS=3 TO ROUND FIELD TO NEAREST EIGHTH VALUE) IDS - INTEGER DECIMAL SCALING (E\&.G\&. IDS=3 TO ROUND FIELD TO NEAREST MILLI-VALUE) (NOTE THAT IDS AND IBS CAN BOTH BE NONZERO, E\&.G\&. IDS=1 AND IBS=1 ROUNDS TO THE NEAREST TWENTIETH) LEN - INTEGER LENGTH OF THE FIELD AND BITMAP MG - INTEGER (LEN) BITMAP IF IBM=1 (0 TO SKIP, 1 TO KEEP) G - REAL (LEN) FIELD
.PP
OUTPUT ARGUMENT LIST: GMIN - REAL MINIMUM VALID ROUNDED FIELD VALUE GMAX - REAL MAXIMUM VALID ROUNDED FIELD VALUE NBIT - INTEGER NUMBER OF BITS TO PACK
.PP
ATTRIBUTES: LANGUAGE: FORTRAN 90 
.PP
Definition at line 35 of file setbit\&.f\&.
.PP
Referenced by putgbexn()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cnvgrib from the source code\&.
