.TH "/home/ed/NCEPLIBS-grib_util/src/tocgrib2/tocgrib2.F90" 3 "Mon Oct 9 2023" "Version 1.3.0" "tocgrib2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/tocgrib2/tocgrib2.F90 \- Create new GRIB2 file with fields from an existing GRIB2 file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBtocgrib2\fP"
.br
.RI "Program reads selected GRIB2 fields from a file, adds a TOC Flag Field separator block and WMO Header in front of each GRIB2 field, and writes them out to a new file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Create new GRIB2 file with fields from an existing GRIB2 file\&. 


.PP
\fBAuthor\fP
.RS 4
Stephen Gilbert 
.RE
.PP
\fBDate\fP
.RS 4
2004-05-17 
.RE
.PP

.PP
Definition in file \fBtocgrib2\&.F90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program tocgrib2"

.PP
Program reads selected GRIB2 fields from a file, adds a TOC Flag Field separator block and WMO Header in front of each GRIB2 field, and writes them out to a new file\&. The output file is in the format required for TOC's FTP Input Service, which can be used to disseminate the GRIB2 bulletins\&. This service is described at http://weather.gov/tg/ftpingest.html\&.
.PP
\fBNote\fP
.RS 4
The 'EXTRACT' variable in the namelist allows users to choose whether they want the entire GRIB2 message containing the requested field (extract=\&.false\&.), OR a GRIB2 message containing only the requested field (extract=\&.true\&.)\&. Both options return the same message if the requested field is the only field in the GRIB2 message\&.
.RE
.PP
.SS "Input Files"
.IP "\(bu" 2
5 namelist of grib fields and associated wmo headers\&.
.IP "\(bu" 2
11 input grib2 file\&.
.IP "\(bu" 2
31 corresponding input grib2 index file\&.
.PP
.SS "Output Files (Including Scratch Files)"
.IP "\(bu" 2
6 standard fortran print file
.IP "\(bu" 2
51 output grib bulletin file in toc format
.PP
.PP
\fBReturns\fP
.RS 4
.IP "\(bu" 2
0 - Successful run
.IP "\(bu" 2
10 - Error opening input GRIB2 data file
.IP "\(bu" 2
20 - Error opening output GRIB transmission file
.IP "\(bu" 2
19 - Error reading control card file - all bulletins missing
.IP "\(bu" 2
30 - Some bulletins are missing
.PP
.RE
.PP
\fBAuthor\fP
.RS 4
Stephen Gilbert 
.RE
.PP
\fBDate\fP
.RS 4
2004-05-17 
.RE
.PP

.PP
Definition at line 36 of file tocgrib2\&.F90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for tocgrib2 from the source code\&.
