.TH "/home/ed/NCEPLIBS-grib_util/src/grib2grib/hexchar.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "grib2grib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/grib2grib/hexchar.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBhexchar\fP (HEX, OUT, IERR)"
.br
.RI "CONVERT 2 CHARACTER HEX NUMBERS (Z2) INTO 1 CHARACTER WITH VALUE OF 0 TO 255 CRAY CFT77 FORTRAN DOES NOT LET YOU READ CHARACTER DATA, OR PRINT CHARACTER DATA WITH A Z2 FORMAT\&. "
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine hexchar (character * 2 HEX, character * 1 OUT,  IERR)"

.PP
CONVERT 2 CHARACTER HEX NUMBERS (Z2) INTO 1 CHARACTER WITH VALUE OF 0 TO 255 CRAY CFT77 FORTRAN DOES NOT LET YOU READ CHARACTER DATA, OR PRINT CHARACTER DATA WITH A Z2 FORMAT\&. 
.PP
Definition at line 8 of file hexchar\&.f\&.
.PP
Referenced by grib2grib()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grib2grib from the source code\&.
