.TH "/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnv22.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "cnvgrib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnv22.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBcnv22\fP (ifl1, ifl2, ipack, usemiss, imiss, table_ver)"
.br
.RI "This subroutine converts every GRIB2 field in a file to another GRIB2 field, most likely one using a different packing option\&. "
.in -1c
.SH "Detailed Description"
.PP 


\&. \&. \&. 
.PP
\fBAuthor\fP
.RS 4
Gilbert 
.RE
.PP
\fBDate\fP
.RS 4
2003-06-11 
.RE
.PP

.PP
Definition in file \fBcnv22\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine cnv22 (integer, intent(in) ifl1, integer, intent(in) ifl2, integer, intent(in) ipack, logical, intent(in) usemiss,  imiss, integer table_ver)"

.PP
This subroutine converts every GRIB2 field in a file to another GRIB2 field, most likely one using a different packing option\&. PROGRAM HISTORY LOG: 2003-06-11 Gilbert 2008-05-14 Vuong - Add missing value management option 0 2009-05-20 Vuong - Initialize variables idsect,local,list_opt
.PP
USAGE: CALL cnv22(ifl1,ifl2,ipack,usemiss,imiss) INPUT ARGUMENT LIST: ifl1 - Fortran unit number of input GRIB2 file ifl2 - Fortran unit number of output GRIB2 file ipack - GRIB2 packing option: 0 = simple packing 2 = group packing 31 = group pack with 1st order differencing 32 = group pack with 2nd order differencing 40 = JPEG2000 encoding 40000 = JPEG2000 encoding (obsolete) 41 = PNG encoding 40010 = PNG encoding (obsolete) if ipack \&.ne\&. one of the values above, 31 is used as a default\&. usemiss - uses missing value management (instead of bitmaps), for use ipack options 2, 31, and 32\&. imiss - Missing value management: 0 = No explicit missing values included within data values 1 = Primary missing values included within data values mastertable_ver_x - Master Table version where x is number from 2 to 10
.PP
INPUT FILES: See ifl1
.PP
OUTPUT FILES: See ifl2
.PP
REMARKS: None
.PP
ATTRIBUTES: LANGUAGE: Fortran 90 MACHINE: IBM SP 
.PP
Definition at line 47 of file cnv22\&.f\&.
.PP
Referenced by cnvgrib()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cnvgrib from the source code\&.
