.TH "/home/ed/NCEPLIBS-grib_util/src/cnvgrib/pds2pdtens.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "cnvgrib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/cnvgrib/pds2pdtens.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpds2pdtens\fP (kpds, kens, kprob, xprob, kclust, kmember, ipdsnum, ipdstmpl, numcoord, coordlist, iret)"
.br
.RI "This routine converts a GRIB1 PDS (Section 1) that includes NCEP ensemble PDS extensions to a GRIB2 PDS (Section 4) info with appropriate Product Definition Template\&. "
.in -1c
.SH "Detailed Description"
.PP 


\&. \&. \&. 
.PP
\fBAuthor\fP
.RS 4
Gilbert 
.RE
.PP
\fBDate\fP
.RS 4
2003-06-12 
.RE
.PP

.PP
Definition in file \fBpds2pdtens\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pds2pdtens (integer, dimension(*), intent(in) kpds, integer, dimension(*), intent(in) kens, integer, dimension(*), intent(in) kprob, real, dimension(*), intent(in) xprob, integer, dimension(*), intent(in) kclust, integer, dimension(*), intent(in) kmember, integer, intent(out) ipdsnum, integer, dimension(*), intent(out) ipdstmpl, integer, intent(out) numcoord, real, dimension(*), intent(out) coordlist, integer, intent(out) iret)"

.PP
This routine converts a GRIB1 PDS (Section 1) that includes NCEP ensemble PDS extensions to a GRIB2 PDS (Section 4) info with appropriate Product Definition Template\&. PROGRAM HISTORY LOG: 2003-06-12 Gilbert 2007-02-07 Gilbert - fixed end date calculation 2007-05-14 Boi Vuong - Added Time Range Indicator 51 (Climatological Mean Value)
.PP
USAGE: CALL pds2pdtens(kpds,kens,kprob,xprob,kclust,kmember, ipdsnum,ipdstmpl,numcoord,coordlist,iret) INPUT ARGUMENT LIST: kpds() - GRIB1 PDS info as specified in W3FI63\&. kens() - Ensemble identification from PDS octets 41-45 kprob() - Ensemble probability info from PDS octets 46 & 47 xprob() - Ensemble probability info from PDS octets 48-55 kclust() - Ensemble cluster info from PDS octets 61-76 kmember()- Ensemble membership info from PDS octest 77-86
.PP
OUTPUT ARGUMENT LIST: ipdsnum - GRIB2 Product Definition Template Number ipdstmpl() - GRIB2 Product Definition Template entries for PDT 4\&.ipdsnum numcoord - number of vertical discretisation values ( not implemented ) coordlist()- vertical discretisation values ( not implemented ) iret - Error return value: 0 = Successful 1 = Unrecognized GRIB1 Time Range Indicator for ensembles 2 = Unrecognized GRIB1 Ensemble type 10 = Unrecognized GRIB1 Time Range Indicator for probabilities
.PP
REMARKS: Use routine pds2pdt for non ensemble related PDS\&.
.PP
ATTRIBUTES: LANGUAGE: Fortran 90 MACHINE: IBM SP 
.PP
Definition at line 44 of file pds2pdtens\&.f\&.
.PP
Referenced by cnv12()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cnvgrib from the source code\&.
