.TH "/home/ed/NCEPLIBS-grib_util/src/copygb2/copygb2.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "copygb2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/copygb2/copygb2.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBcopygb2\fP"
.br
.RI "The command copygb2 copies all or part of one GRIB2 file to another GRIB2 file, interpolating if necessary\&. "
.ti -1c
.RI "subroutine \fBcpgb\fP (LG1, LX1, LGB, LXB, LGM, LXM, LG2, IGDTN, KGDTI, IP, IPOPT, JPDTN, JPDT, NUV, IUV, JPDSB, JB, JBK, LAB, AB, LAM, AM, LXX, LWG, IDS, IBS, NBS)"
.br
.ti -1c
.RI "subroutine \fBcpgb1\fP (LG1, LX1, M1, MBUF, MF, MI, IGDTN, KGDTI, IP, IPOPT, JPDTN, JPDT, NUV, IUV, JPDSB, JB, JBK, LAB, AB, LAM, AM, IDS, IBS, NBS, LGB, LXB, MB, CBUFB, NLENB, NNUMB, MNUMB, LGM, LXM, MM, LG2, LXX, KS1, NO, IRET)"
.br
.ti -1c
.RI "subroutine \fBeusage\fP"
.br
.ti -1c
.RI "subroutine \fBintgrib1\fP (K1F, KGDS1F, K2F, KGDS2F, MRL, MRO, IV, IP, IPOPT, KGDS1, K1, IB1, L1, F1, G1, KGDS2, K2, IB2, L2, F2, G2, IRET)"
.br
.ti -1c
.RI "subroutine \fBintgrib2\fP (IV, IP, IPOPT, NGDT1, KGDT1, IDEFN1, IDEF1, K1, IB1, L1, F1, G1, NGDT2, KGDT2, K2, IB2, L2, F2, G2, IRET)"
.br
.ti -1c
.RI "function \fBlengdsf\fP (KGDS, KGDSF)"
.br
.ti -1c
.RI "function \fBnumpts\fP (IGDTN, KGDT)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
IREDELL 
.RE
.PP
\fBDate\fP
.RS 4
1998-10-22 
.RE
.PP

.PP
Definition in file \fBcopygb2\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program copygb2"

.PP
The command copygb2 copies all or part of one GRIB2 file to another GRIB2 file, interpolating if necessary\&. Unless otherwise directed (-x option), the GRIB2 index file is also used to speed the reading\&. The fields are interpolated to an output grid if specified (-g option)\&. The interpolation type defaults to bilinear but may be specified directly (-i option)\&. The copying may be limited to specific fields (-k option)\&. It may also be limited to a specified subgrid of the output grid or to a subrange of the input fields (-B and -b, -A, and -K options)\&. Fields can be identified as scalars or vectors (-v option), which are interpolated differently\&. The invalid data in the output field can be filled with mask values or merged with a merge field (-M and -m options)\&. The output GRIB2 message can also be appended to a file (-a option)\&. Some defaults can be overridden in a namelist file (-N option)\&.
.PP
PROGRAM HISTORY LOG:
.IP "\(bu" 2
96-07-19 IREDELL
.IP "\(bu" 2
97-03-05 IREDELL CORRECTED THE COPYING OF THE V-WIND FIELD
.IP "\(bu" 2
WHEN NO INTERPOLATION IS DONE
.IP "\(bu" 2
97-03-18 IREDELL INCREASED VERBOSITY
.IP "\(bu" 2
1998-09-03 IREDELL INSTRUMENTED AND MADE PLATFORM-INDEPENDENT
.IP "\(bu" 2
1999-10-05 IREDELL ADDED APPEND OPTION AND WGRIB REQUEST OPTION
.IP "\(bu" 2
1999-10-06 IREDELL ADDED MERGE OPTION
.IP "\(bu" 2
2000-01-19 IREDELL ADDED NAMELIST OPTION
.IP "\(bu" 2
2001-03-16 IREDELL ADDED ENSEMBLE EXTENSION OPTION
.IP "\(bu" 2
2002-01-10 IREDELL CORRECTED V-WIND SEARCH TO INCLUDE SUBCENTER
.IP "\(bu" 2
2005-02-17 GILBERT MODIFIED FROM COPYGB FOR USE WITH GRIB2 FILES\&.
.IP "\(bu" 2
2012-10-03 VUONG MODIFIED TO REMOVE DEALLOCATE L1I,F1I,G1I
.IP "\(bu" 2
2013-05-08 VUONG INITIALIZED VARIABLES MM AND ALLONES TO ZERO
.IP "\(bu" 2
2016-10-03 VUONG INITIALIZED POINTERS AND HOW THEY ARE ASSOCIATED CHANGED FROM ALLOCATE(L1I(MI),F1I(MI),G1I(MI)) TO ALLOCATE(L1I(MI)),ALLOCATE(F1I(MI)),ALLOCATE(G1I(MI))
.PP
.SS "COMMAND LINE OPTIONS:"
-a Appends rather than overwrites the output GRIB file\&.
.PP
-A '<> mapthreshold' Inequality and threshold used in determining where on the map the data will be copied\&. The data are copied only where the given map field is on the correct side of the threshold\&. The mapthreshold defaults to '>-1\&.e30'; in this case, only the map field's bitmap will limit the domain\&.
.PP
-b mapindex 
.br
 Optional index file used to get the map field\&.
.PP
-B mapgrib 
.br
 GRIB file used to get the map field\&. The map field is read from the GRIB file and compared to the map threshold to determine for which region on the map the data will be copied\&. The mapgrib can be the name of an actual GRIB file (in which case the index file may be specified with the -b option) or it can be '-1'\&. If mapgrib is '-1', then the input GRIB file (first positional argument) is used\&. The -K option specifies which field to read from the mapgrib GRIB file\&. If mapgrib is an actual file, then the first field is taken if -K is not specified\&. On the other hand, if mapgrib is '-1', then if the if -K is not specified, the current field is taken as the map field\&. A special exception is if -K '-1' is specified, in which case the current field is taken as the map field and it is applied before any interpolation; otherwise the map field is always applied after interpolation\&.
.PP
-g 'kgdtn [kgds]' Output grid identification\&. If kgdtn=-1 (the default), then the output grid is the same as the input grid\&. If kgdtn=-4, then the grid is that of the map field\&. If kgdtn=-5, then the grid is that of the merge field\&. If 0<=kgdtn<65535, then grid designates a specific GRIB2 Grid Definition Template (GDT) Number\&. In this case, kgdt is the list of the full set of Grid Definition Template values for the GDT 3\&.kgdtn, defining the output grid\&.
.PP
-i 'ip [ipopts]' Interpolation options\&. The default is bilinear interpolation (ip=0)\&. Other interpolation options are bicubic (ip=1), neighbor (ip=2), budget (ip=3), and spectral (ip=4)\&. Spectral interpolation is forced even if the input and output grids are the same\&. See the documentation for iplib for further details\&.
.PP
-k 'kpdtn kpdt' Full set of Production Definition Template parameters determining the field(s) to be copied\&. kpdtn is Product Definition Template (PDT) number 4\&.kpdtn\&. A wildcard, indicating search all template numbers, is specified by -1 (the default)\&. The kpdt array contains the values of each entry of PDT 4\&.kpdtn, and a wildcard for any entry can be specified as -9999\&. If the -k is not specified, then copygb will attempt to copy every field in the input GRIB file\&.
.PP
-K 'mapkpds' Full set of kpds parameters determing a GRIB PDS (product definition section) in the W3FI63 format determining the map field to be used to determine where on the map the data will be copied\&. 
.br
 A wildcard is specified by -1 (the defaults)\&.
.PP
-m mergeindex 
.br
 Optional index file used to get the merge field\&.
.PP
-M 'mask'/mergegrib Mask used to fill out bitmapped areas of the map\&. If specified, there will be no bitmap in the output\&. The mask must be in the format '#value' where value is the real number used to fill out the field\&. Otherwise, the argument is interpreted as a merge GRIB file\&. Then for each GRIB message copied, a merge field is found in the merge GRIB file with the same parameter and level indicators as the copied field\&. This merge field is interpolated to the output grid and used to fill out the bitmapped areas of the map, at least where the merge field is not bitmapped\&. No merging is done if no merge field is found\&.
.PP
-N namelist Namelist file to override default output options\&. The namelist must start with ' &NLCOPYGB' and end with '/'\&. Namelist variables are IDS(255) Output decimal scaling by parameter IBS(255) Output binary scaling by parameter NBS(255) Output number of bits by parameter
.PP
-v 'uparms' Parameter indicator(s) for the u-component of vectors\&. A specific parameter is indicated by three numbers: disc|cat|num\&. Any parameter value in uparms is defined as (65536*disc)+(256*cat)+num\&. The parameter indicator for the v-component is assumed to be one more than that of the u-component\&. If the -v option is not specified, then the wind components (parameters 0|2|2 = 514 and 0|2|3 = 515) are the only fields assumed to be vector components in the GRIB file\&.
.PP
-x Turns off the use of an index file\&. The index records are then extracted from the GRIB file, which will increase the time taken by copygb2\&.
.PP
-X Turns on verbose printout\&. This option is incompatible with GRIB output to standard output\&.
.PP
INPUT FILES:
.IP "\(bu" 2
UNIT 11 INPUT GRIB FILE
.IP "\(bu" 2
UNIT 14 MAP GRIB FILE
.IP "\(bu" 2
UNIT 15 MERGE GRIB FILE
.IP "\(bu" 2
UNIT 31 INPUT GRIB INDEX FILE
.IP "\(bu" 2
UNIT 34 MAP GRIB INDEX FILE
.IP "\(bu" 2
UNIT 35 MERGE GRIB INDEX FILE
.PP
.PP
OUTPUT FILES:
.IP "\(bu" 2
UNIT 51 OUTPUT GRIB FILE
.PP
.PP
SUBPROGRAMS CALLED:
.IP "\(bu" 2
IARGC
.IP "\(bu" 2
GETARG
.IP "\(bu" 2
ERRMSG
.IP "\(bu" 2
EUSAGE
.IP "\(bu" 2
ERREXIT
.IP "\(bu" 2
FPARSEI
.IP "\(bu" 2
FPARSER
.IP "\(bu" 2
BAOPENR
.IP "\(bu" 2
BAOPENWT
.IP "\(bu" 2
BAOPENWA
.IP "\(bu" 2
CPGB 
.PP

.PP
Definition at line 181 of file copygb2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for copygb2 from the source code\&.
