.TH "/home/ed/NCEPLIBS-grib_util/src/grb2index/grb2index.F90" 3 "Fri Mar 22 2024" "Version 1.4.0" "grb2index" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/grb2index/grb2index.F90 \- Write a GRIB2 index file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBgrb2index\fP"
.br
.RI "This program creates an index file from a GRIB2 file\&. "
.ti -1c
.RI "integer function \fBncbase\fP (c, n)"
.br
.RI "Locate basename of a file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Write a GRIB2 index file\&. 


.PP
\fBAuthor\fP
.RS 4
Iredell 
.RE
.PP
\fBDate\fP
.RS 4
1992-11-22 
.RE
.PP

.PP
Definition in file \fBgrb2index\&.F90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program grb2index"

.PP
This program creates an index file from a GRIB2 file\&. 
.PP
\fBReturns\fP
.RS 4

.IP "\(bu" 2
0 successful run
.IP "\(bu" 2
1 GRIB message not found
.IP "\(bu" 2
2 incorrect arguments
.IP "\(bu" 2
8 error accessing file
.PP
.RE
.PP
\fBAuthor\fP
.RS 4
Iredell 
.RE
.PP
\fBDate\fP
.RS 4
1992-11-22 
.RE
.PP

.PP
Definition at line 14 of file grb2index\&.F90\&.
.PP
References ncbase()\&.
.SS "integer function ncbase (character, dimension(*) c, integer n)"

.PP
Locate basename of a file\&. This subprogram locates the character number after the last '/' in a character string\&. For unix filenames, the character number returned marks the beginning of the basename of the file\&.
.PP
\fBParameters\fP
.RS 4
\fIc\fP character string to search 
.br
\fIn\fP integer length of string
.RE
.PP
\fBReturns\fP
.RS 4
The index of the basename within the string\&.
.RE
.PP
\fBAuthor\fP
.RS 4
Iredell 
.RE
.PP
\fBDate\fP
.RS 4
93-11-22 
.RE
.PP

.PP
Definition at line 93 of file grb2index\&.F90\&.
.PP
Referenced by grb2index()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grb2index from the source code\&.
