.TH "/home/ed/NCEPLIBS-grib_util/src/tocgrib/makwmo.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "tocgrib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/tocgrib/makwmo.f \- FORMAT THE WMO HEADER\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBmakwmo\fP (BULHED, IDAY, IHOUR, KWBX, HEADER)"
.br
.RI "FORMS THE WMO HEADER FOR A GIVEN BULLETIN\&. "
.in -1c
.SH "Detailed Description"
.PP 
FORMAT THE WMO HEADER\&. 


.PP
\fBAuthor\fP
.RS 4
FARLEY 
.RE
.PP
\fBDate\fP
.RS 4
84-07-06 
.RE
.PP

.PP
Definition in file \fBmakwmo\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine makwmo (character * 6 BULHED,  IDAY,  IHOUR, character * 4 KWBX, character * 1, dimension (*) HEADER)"

.PP
FORMS THE WMO HEADER FOR A GIVEN BULLETIN\&. PROGRAM HISTORY LOG:
.IP "\(bu" 2
84-07-06 FARLEY ORIGINAL AUTHOR
.IP "\(bu" 2
94-10-10 R\&.E\&.JONES CHANGES FOR CRAY
.IP "\(bu" 2
95-10-18 R\&.E\&.JONES ADD PARAMETER KWBX TO CALL
.IP "\(bu" 2
98-06-16 Gilbert Changed argument list to pass in day and hour instead of the old O\&.N\&. 84 date word\&.
.IP "\(bu" 2
2003-03-28 Gilbert Removed equivalences\&.
.PP
.PP
\fBParameters\fP
.RS 4
\fIBULHED\fP - TTAAII BULLETIN HEADER FT10 
.br
\fIIDAY\fP - Day of Month 
.br
\fIIHOUR\fP - Hour of Day\&. 
.br
\fIKWBX\fP - 4 CHARACTERS (KWBC TO KWBQ) 
.br
\fIHEADER\fP - COMPLETE WMO HEADER IN ASCII 
.RE
.PP

.PP
Definition at line 21 of file makwmo\&.f\&.
.PP
Referenced by tocgrib()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for tocgrib from the source code\&.
