/home/ed/NCEPLIBS-grib_util/src/copygb/copygb.F90
NAME
/home/ed/NCEPLIBS-grib_util/src/copygb/copygb.F90 - Compare grib files.
SYNOPSIS
Functions/Subroutines
program copygb
The command copygb copies all or part of one GRIB file to another GRIB file, interpolating if necessary.
subroutine cpgb (LG1, LX1, LGB, LXB, LGM, LXM, LG2, IGI, KGDSI, IP, IPOPT, JPDS1, NUV, IUV, JPDSB, JB, JBK, LAB, AB, LAM, AM, LXX, LWG, IDS, IBS, NBS)
Copy grib files.
subroutine cpgb1 (LG1, LX1, M1, CBUF1, NLEN1, NNUM1, MNUM1, MBUF, MF, MI, IGI, KGDSI, IP, IPOPT, JPDS1, NUV, IUV, JPDSB, JB, JBK, LAB, AB, LAM, AM, IDS, IBS, NBS, LGB, LXB, MB, CBUFB, NLENB, NNUMB, MNUMB, LGM, LXM, MM, CBUFM, NLENM, NNUMM, MNUMM, LG2, LXX, KS1, NO, IRET)
Copy one grib field.
subroutine eusage
Print proper usage to stderr.
subroutine intgrib (IV, IP, IPOPT, KGDS1, K1, IB1, L1, F1, G1, KGDS2, K2, IB2, L2, F2, G2, IRET)
Interpolate field.
subroutine intgrib1 (K1F, KGDS1F, K2F, KGDS2F, MRL, MRO, IV, IP, IPOPT, KGDS1, K1, IB1, L1, F1, G1, KGDS2, K2, IB2, L2, F2, G2, IRET)
Interpolate field.
function lengdsf (KGDS, KGDSF)
Return the length of a filled grid.
Detailed Description
Compare grib files.
Author
Mark Iredell
Date
1998-10-22
Definition in file copygb.F90.
Function/Subroutine Documentation
program copygb
The command copygb copies all or part of one GRIB file to another GRIB file, interpolating if necessary. Unless otherwise directed (-x option), the GRIB index file is also used to speed the reading. The fields are interpolated to an output grid if specified (-g option). The interpolation type defaults to bilinear but may be specified directly (-i option). The copying may be limited to specific fields (-k option). It may also be limited to a specified subgrid of the output grid or to a subrange of the input fields (-B and -b, -A, and -K options). Fields can be identified as scalars or vectors (-v option), which are interpolated differently. The invalid data in the output field can be filled with mask values or merged with a merge field (-M and -m options). The output GRIB message can also be appended to a file (-a option). Some defaults can be overridden in a namelist file (-N option).
Command Line Options
-a Appends rather than overwrites the output GRIB file.
-A '<> mapthreshold' Inequality and threshold used in determining where on the map the data will be copied. The data are copied only where the given map field is on the correct side of the threshold. The mapthreshold defaults to '>-1.e30'; in this case, only the map field's bitmap will limit the domain.
-b mapindex Optional index file used to get the map field.
-B mapgrib GRIB file used to get the map field. The map field is read from the GRIB file and compared to the map threshold to determine for which region on the map the data will be copied. The mapgrib can be the name of an actual GRIB file (in which case the index file may be specified with the -b option) or it can be '-1'. If mapgrib is '-1', then the input GRIB file (first positional argument) is used. The -K option specifies which field to read from the mapgrib GRIB file. If mapgrib is an actual file, then the first field is taken if -K is not specified. On the other hand, if mapgrib is '-1', then if the if -K is not specified, the current field is taken as the map field. A special exception is if -K '-1' is specified, in which case the current field is taken as the map field and it is applied before any interpolation; otherwise the map field is always applied after interpolation.
-g 'grid [kgds]' Output grid identification. If grid=-1 (the default), then the output grid is the same as the input grid. If grid=-4, then the grid is that of the map field. If grid=-5, then the grid is that of the merge field. If 0<grid<255, then grid designates an NCEP grid. If grid=255, then the grid must be specified by the full set of kgds parameters determining a GRIB GDS (grid description section) in the W3FI63 format.
-i 'ip [ipopts]' Interpolation options. The default is bilinear interpolation (ip=0). Other interpolation options are bicubic (ip=1), neighbor (ip=2), budget (ip=3), and spectral (ip=4). Spectral interpolation is forced even if the input and output grids are the same. See the documentation for iplib for further details.
-k 'kpds' Full set of kpds parameters determing a GRIB PDS (product definition section) in the W3FI63 format determining the field(s) to be copied. Note that kpds(5) is the parameter indicator (PDS octet 9). A wildcard is specified by -1 (the defaults). If 'kpds' is equal to 'w', then the requested record numbers are read in from standard input instead, one record per line and possibly delimited by a colon (so that wgrib could pipe requests to copygb). If the -k is not specified, then copygb will attempt to copy every field in the input GRIB file.
-K 'mapkpds' Full set of kpds parameters determing a GRIB PDS (product definition section) in the W3FI63 format determining the map field to be used to determine where on the map the data will be copied. A wildcard is specified by -1 (the defaults).
-m mergeindex Optional index file used to get the merge field.
-M 'mask'/mergegrib Mask used to fill out bitmapped areas of the map. If specified, there will be no bitmap in the output. The mask must be in the format '#value' where value is the real number used to fill out the field. Otherwise, the argument is interpreted as a merge GRIB file. Then for each GRIB message copied, a merge field is found in the merge GRIB file with the same parameter and level indicators as the copied field. This merge field is interpolated to the output grid and used to fill out the bitmapped areas of the map, at least where the merge field is not bitmapped. No merging is done if no merge field is found.
-N namelist Namelist file to override default output options. The namelist must start with ' &NLCOPYGB' and end with '/'. Namelist variables are IDS(255) Output decimal scaling by parameter IBS(255) Output binary scaling by parameter NBS(255) Output number of bits by parameter
-v 'uparms' Parameter indicator(s) for the u-component of vectors. The parameter indicator for the v-component is assumed to be one more than that of the u-component. If the -v option is not specified, then the wind components (parameters 33 and 34) are the only fields assumed to be vector components in the GRIB file.
-x Turns off the use of an index file. The index records are then extracted from the GRIB file, which will increase the time taken by copygb.
-X Turns on verbose printout. This option is incompatible with GRIB output to standard output.
Input Files
unit 11 input grib file
unit 14 map grib file
unit 15 merge grib file
unit 31 input grib index file
unit 34 map grib index file
unit 35 merge grib index file
output files
unit 51 output grib file
Returns
0 for success.
Author
Stephen Gilbert
Date
2000-05-02
Definition at line 149 of file copygb.F90.
References cpgb(), and eusage().
subroutine cpgb ( LG1, LX1, LGB, LXB, LGM, LXM, LG2, IGI, integer, dimension(200) KGDSI, IP, integer, dimension(20) IPOPT, integer, dimension(100) JPDS1, NUV, integer, dimension(100) IUV, integer, dimension(100) JPDSB, JB, JBK, LAB, AB, LAM, AM, LXX, LWG, integer, dimension(255) IDS, integer, dimension(255) IBS, integer, dimension(255) NBS)
Copy grib files.
Parameters
lg1 integer unit number for grib file 1
lx1 integer unit number for grib index file 1
lgb integer unit number for grib file map
lxb integer unit number for grib index file map
lgm integer unit number for grib file merge
lxm integer unit number for grib index file merge
lg2 integer unit number for grib file 2
igi integer output grid identification
kgdsi integer (200) output grid parameters
ip integer interpolation type
ipopt integer (20) interpolation options
jpds1 integer (100) kpds search options
nuv integer number of vector parameter ids
iuv integer (100) vector parameter ids
jpdsb integer (100) kpds search options (map)
jb integer flag for map optiion
jbk integer flag for map optiion
lab integer flag for map threshold inequality
ab real map threshold
lam integer flag for mask value
am real mask value
lxx integer flag for verbose output
lwg integer flag for stdin selection
ids integer (255) decimal scaling (-9999 for no change)
ibs integer (255) binary scaling (-9999 for no change)
nbs integer (255) number of bits (-9999 for no change)
Author
Iredell
Date
96-07-19
Definition at line 563 of file copygb.F90.
References cpgb1().
Referenced by copygb().
subroutine cpgb1 ( LG1, LX1, M1, character, dimension(mbuf) CBUF1, NLEN1, NNUM1, MNUM1, MBUF, MF, MI, IGI, integer, dimension(200) KGDSI, IP, integer, dimension(20) IPOPT, integer, dimension(100) JPDS1, NUV, integer, dimension(100) IUV, integer, dimension(100) JPDSB, JB, JBK, LAB, AB, LAM, AM, integer, dimension(255) IDS, integer, dimension(255) IBS, integer, dimension(255) NBS, LGB, LXB, MB, character, dimension(mbuf) CBUFB, NLENB, NNUMB, MNUMB, LGM, LXM, MM, character, dimension(mbuf) CBUFM, NLENM, NNUMM, MNUMM, LG2, LXX, KS1, NO, IRET)
Copy one grib field.
Parameters
lg1 integer unit number for grib file 1
lx1 integer unit number for grib index file 1
m1 integer dimension of grib field 1
cbuf1 character (mbuf) index buffer 1
nlen1 integer record length of index buffer 1
nnum1 integer number of index records 1
mnum1 integer number of index records 1 skipped
mbuf integer dimension of index buffers
mf integer dimension of field
mi integer dimension of output grid
igi integer output grid identification
kgdsi integer (200) output grid parameters
ip integer interpolation type
ipopt integer (20) interpolation options
jpds1 integer (100) kpds search options
nuv integer number of vector parameter ids
iuv integer (100) vector parameter ids
jpdsb integer (100) kpds search options (map)
jb integer flag for map optiion
jbk integer flag for map optiion
lab integer flag for map threshold inequality
ab real map threshold
lam integer flag for mask value
am real mask value
ids integer (255) decimal scaling (-9999 for no change)
ibs integer (255) binary scaling (-9999 for no change)
nbs integer (255) number of bits (-9999 for no change)
lgb integer unit number for grib file map
lxb integer unit number for grib index file map
mb integer dimension of grib field map
cbufb character (mbuf) index buffer map
nlenb integer record length of index buffer map
nnumb integer number of records in index buffer map
mnumb integer number of index records map skipped
lgm integer unit number for grib file merge
lxm integer unit number for grib index file merge
mm integer dimension of grib field merge
cbufm character (mbuf) index buffer merge
nlenm integer record length of index buffer merge
nnumm integer number of records in index buffer merge
mnumm integer number of index records merge skipped
lg2 integer unit number for grib file 2
lxx integer flag for verbose output
ks1 integer input record counter
no integer output record counter
iret integer return code
Author
Iredell
Date
96-07-19
Definition at line 780 of file copygb.F90.
References intgrib().
Referenced by cpgb().
subroutine eusage
Print proper usage to stderr.
Author
Iredell
Date
96-07-19
Definition at line 514 of file copygb.F90.
Referenced by copygb().
subroutine intgrib ( IV, IP, integer, dimension(20) IPOPT, integer, dimension(200) KGDS1, K1, IB1, logical*1, dimension(k1) L1, real, dimension(k1) F1, real, dimension(k1) G1, integer, dimension(200) KGDS2, K2, IB2, logical*1, dimension(k2) L2, real, dimension(k2) F2, real, dimension(k2) G2, IRET)
Interpolate field.
Parameters
iv integer vector flag
ip integer interpolation type
ipopt integer (20) interpolation options
kgds1 integer (200) input grid parameters
k1 integer input dimension
ib1 integer input bitmap flag
l1 logical*1 (k1) input bitmap if ib1=1
f1 real (k1) input field
g1 real (k1) input y-component if iv=1
kgds2 integer (200) output grid parameters
k2 integer output dimension
ib2 integer output bitmap flag
l2 logical*1 (k2) output bitmap
f2 real (k2) output field
g2 real (k2) output y-component if iv=1
iret integer return code
Author
Iredell
Date
96-07-19
Definition at line 1094 of file copygb.F90.
References intgrib1(), and lengdsf().
Referenced by cpgb1().
subroutine intgrib1 ( K1F, integer, dimension(200) KGDS1F, K2F, integer, dimension(200) KGDS2F, MRL, MRO, IV, IP, integer, dimension(20) IPOPT, integer, dimension(200) KGDS1, K1, IB1, logical*1, dimension(k1) L1, real, dimension(k1) F1, real, dimension(k1) G1, integer, dimension(200) KGDS2, K2, IB2, logical*1, dimension(k2) L2, real, dimension(k2) F2, real, dimension(k2) G2, IRET)
Interpolate field.
Parameters
k1f integer regularized input dimension
kgds1f integer (200) regularized input grid parameters
k2f integer regularized output dimension
kgds2f integer (200) regularized output grid parameters
mrl integer dimension of rlat and rlon
mro integer dimension of crot and srot
iv integer vector flag
ip integer interpolation type
ipopt integer (20) interpolation options
kgds1 integer (200) input grid parameters
k1 integer input dimension
ib1 integer input bitmap flag
l1 logical*1 (k1) input bitmap if ib1=1
f1 real (k1) input field
g1 real (k1) input y-component if iv=1
kgds2 integer (200) output grid parameters
k2 integer output dimension
ib2 integer output bitmap flag
l2 logical*1 (k2) output bitmap
f2 real (k2) output field
g2 real (k2) output y-component if iv=1
iret integer return code
Author
Iredell
Date
96-07-19
Definition at line 1173 of file copygb.F90.
Referenced by intgrib().
function lengdsf (integer, dimension(200) KGDS, integer, dimension(200) KGDSF)
Return the length of a filled grid. Given a grid description section (in w3fi63 format), return the grid description section and size of its regularized counterpart. That is, if the input grid is regular, then itself is returned along with its grid size; however if the input grid is only quasi-regular (such as the wafs grids), then its filled regular version is returned along with its filled grid size.
Parameters
kgds integer (200) gds parameters in w3fi63 format
kgdsf integer (200) regular gds parameters in w3fi63 format
Returns
integer size of regularized grid
Author
Mark Iredell
Date
96-07-19
Definition at line 1344 of file copygb.F90.
Referenced by intgrib().
Author
Generated automatically by Doxygen for copygb from the source code.