/home/ed/NCEPLIBS-grib_util/src/copygb2/copygb2.F90
NAME
/home/ed/NCEPLIBS-grib_util/src/copygb2/copygb2.F90 - Copy all or part of one GRIB2 file to another GRIB2 file.
SYNOPSIS
Functions/Subroutines
program copygb2
The command copygb2 copies all or part of one GRIB2 file to another GRIB2 file, interpolating if necessary.
subroutine cpgb (LG1, LX1, LGB, LXB, LGM, LXM, LG2, IGDTN, KGDTI, IP, IPOPT, JPDTN, JPDT, NUV, IUV, JPDSB, JB, JBK, LAB, AB, LAM, AM, LXX, LWG, IDS, IBS, NBS)
Copy grib files.
subroutine cpgb1 (LG1, LX1, M1, MBUF, MF, MI, IGDTN, KGDTI, IP, IPOPT, JPDTN, JPDT, NUV, IUV, JPDSB, JB, JBK, LAB, AB, LAM, AM, IDS, IBS, NBS, LGB, LXB, MB, CBUFB, NLENB, NNUMB, MNUMB, LGM, LXM, MM, LG2, LXX, KS1, NO, IRET)
Copy one grib field.
subroutine eusage
Print proper usage to stderr.
subroutine intgrib1 (K1F, KGDS1F, K2F, KGDS2F, MRL, MRO, IV, IP, IPOPT, KGDS1, K1, IB1, L1, F1, G1, KGDS2, K2, IB2, L2, F2, G2, IRET)
Interpolate field.
subroutine intgrib2 (IV, IP, IPOPT, NGDT1, KGDT1, IDEFN1, IDEF1, K1, IB1, L1, F1, G1, NGDT2, KGDT2, K2, IB2, L2, F2, G2, IRET)
Interpolate field.
function lengdsf (KGDS, KGDSF)
Return the length of a filled grid.
function numpts (IGDTN, KGDT)
Return the number of points in a grid.
Detailed Description
Copy all or part of one GRIB2 file to another GRIB2 file.
Author
Iredell
Date
1998-10-22
Definition in file copygb2.F90.
Function/Subroutine Documentation
program copygb2
The command copygb2 copies all or part of one GRIB2 file to another GRIB2 file, interpolating if necessary. Unless otherwise directed (-x option), the GRIB2 index file is also used to speed the reading.
The fields are interpolated to an output grid if specified (-g option). The interpolation type defaults to bilinear but may be specified directly (-i option).
The copying may be limited to specific fields (-k option). It may also be limited to a specified subgrid of the output grid or to a subrange of the input fields (-B and -b, -A, and -K options). Fields can be identified as scalars or vectors (-v option), which are interpolated differently. The invalid data in the output field can be filled with mask values or merged with a merge field (-M and -m options).
The output GRIB2 message can also be appended to a file (-a option).
Some defaults can be overridden in a namelist file (-N option).
COMMAND LINE OPTIONS:
-a Appends rather than overwrites the output GRIB file.
-A '<> mapthreshold' Inequality and threshold used in determining where on the map the data will be copied. The data are copied only where the given map field is on the correct side of the threshold. The mapthreshold defaults to '>-1.e30'; in this case, only the map field's bitmap will limit the domain.
-b mapindex Optional index file used to get the map field.
-B mapgrib GRIB file used to get the map field. The map field is read from the GRIB file and compared to the map threshold to determine for which region on the map the data will be copied. The mapgrib can be the name of an actual GRIB file (in which case the index file may be specified with the -b option) or it can be '-1'. If mapgrib is '-1', then the input GRIB file (first positional argument) is used. The -K option specifies which field to read from the mapgrib GRIB file. If mapgrib is an actual file, then the first field is taken if -K is not specified. On the other hand, if mapgrib is '-1', then if the if -K is not specified, the current field is taken as the map field. A special exception is if -K '-1' is specified, in which case the current field is taken as the map field and it is applied before any interpolation; otherwise the map field is always applied after interpolation.
-g 'kgdtn [kgds]' Output grid identification. If kgdtn=-1 (the default), then the output grid is the same as the input grid. If kgdtn=-4, then the grid is that of the map field. If kgdtn=-5, then the grid is that of the merge field. If 0<=kgdtn<65535, then grid designates a specific GRIB2 Grid Definition Template (GDT) Number. In this case, kgdt is the list of the full set of Grid Definition Template values for the GDT 3.kgdtn, defining the output grid.
-i 'ip [ipopts]' Interpolation options. The default is bilinear interpolation (ip=0). Other interpolation options are bicubic (ip=1), neighbor (ip=2), budget (ip=3), and spectral (ip=4). Spectral interpolation is forced even if the input and output grids are the same. See the documentation for iplib for further details.
-k 'kpdtn kpdt' Full set of Production Definition Template parameters determining the field(s) to be copied. kpdtn is Product Definition Template (PDT) number 4.kpdtn. A wildcard, indicating search all template numbers, is specified by -1 (the default). The kpdt array contains the values of each entry of PDT 4.kpdtn, and a wildcard for any entry can be specified as -9999. If the -k is not specified, then copygb will attempt to copy every field in the input GRIB file.
-K 'mapkpds' Full set of kpds parameters determing a GRIB PDS (product definition section) in the W3FI63 format determining the map field to be used to determine where on the map the data will be copied. A wildcard is specified by -1 (the defaults).
-m mergeindex Optional index file used to get the merge field.
-M 'mask'/mergegrib Mask used to fill out bitmapped areas of the map. If specified, there will be no bitmap in the output. The mask must be in the format '#value' where value is the real number used to fill out the field. Otherwise, the argument is interpreted as a merge GRIB file. Then for each GRIB message copied, a merge field is found in the merge GRIB file with the same parameter and level indicators as the copied field. This merge field is interpolated to the output grid and used to fill out the bitmapped areas of the map, at least where the merge field is not bitmapped. No merging is done if no merge field is found.
-N namelist Namelist file to override default output options. The namelist must start with ' &NLCOPYGB' and end with '/'. Namelist variables are IDS(255) Output decimal scaling by parameter IBS(255) Output binary scaling by parameter NBS(255) Output number of bits by parameter
-v 'uparms' Parameter indicator(s) for the u-component of vectors. A specific parameter is indicated by three numbers: disc|cat|num. Any parameter value in uparms is defined as (65536*disc)+(256*cat)+num. The parameter indicator for the v-component is assumed to be one more than that of the u-component. If the -v option is not specified, then the wind components (parameters 0|2|2 = 514 and 0|2|3 = 515) are the only fields assumed to be vector components in the GRIB file.
-x Turns off the use of an index file. The index records are then extracted from the GRIB file, which will increase the time taken by copygb2.
-X Turns on verbose printout. This option is incompatible with GRIB output to standard output.
Files
Input Files
unit 11 input grib file
unit 14 map grib file
unit 15 merge grib file
unit 31 input grib index file
unit 34 map grib index file
unit 35 merge grib index file
Output Files
unit 51 output grib file
Returns
0 for success.
Author
Iredell
Date
1998-10-22
Definition at line 161 of file copygb2.F90.
References cpgb(), eusage(), and numpts().
subroutine copygb2::cpgb ( LG1, LX1, LGB, LXB, LGM, LXM, LG2, IGDTN, integer, dimension(200) KGDTI, IP, integer, dimension(20) IPOPT, JPDTN, integer, dimension(200) JPDT, NUV, integer, dimension(100) IUV, integer, dimension(100) JPDSB, JB, JBK, LAB, AB, LAM, AM, LXX, LWG, integer, dimension(255) IDS, integer, dimension(255) IBS, integer, dimension(255) NBS)
Copy grib files.
Parameters
lg1 integer unit number for grib file 1
lx1 integer unit number for grib index file 1
lgb integer unit number for grib file map
lxb integer unit number for grib index file map
lgm integer unit number for grib file merge
lxm integer unit number for grib index file merge
lg2 integer unit number for grib file 2
igdtn integer output grid identification
kgdti integer (200) output grid definition template values
ip integer interpolation type
ipopt integer (20) interpolation options
jpdtn integer product definition template number search options
jpdt integer (100) product definition template values search options
nuv integer number of vector parameter ids
iuv integer (100) vector parameter ids
jpdsb integer (100) kpds search options (map)
jb integer flag for map option
jbk integer flag for map option
lab integer flag for map threshold inequality
ab real map threshold
lam integer flag for mask value
am real mask value
lxx integer flag for verbose output
lwg integer flag for stdin selection
ids integer (255) decimal scaling (-9999 for no change)
ibs integer (255) binary scaling (-9999 for no change)
nbs integer (255) number of bits (-9999 for no change)
Author
Iredell
Date
96-07-19
Definition at line 586 of file copygb2.F90.
References cpgb1(), and numpts().
Referenced by copygb2().
subroutine copygb2::cpgb1 ( LG1, LX1, M1, MBUF, MF, MI, IGDTN, integer, dimension(200), target KGDTI, IP, integer, dimension(20) IPOPT, JPDTN, integer, dimension(100) JPDT, NUV, integer, dimension(100) IUV, integer, dimension(100) JPDSB, JB, JBK, LAB, AB, LAM, AM, integer, dimension(255) IDS, integer, dimension(255) IBS, integer, dimension(255) NBS, LGB, LXB, MB, character, dimension(mbuf) CBUFB, NLENB, NNUMB, MNUMB, LGM, LXM, MM, LG2, LXX, KS1, NO, IRET)
Copy one grib field.
Parameters
lg1 integer unit number for grib file 1
lx1 integer unit number for grib index file 1
m1 integer dimension of grib field 1
mbuf integer dimension of index buffers
mf integer dimension of field
mi integer dimension of output grid
igdtn integer output grid definition template number
kgdti integer (200) output grid definition template values
ip integer interpolation type
ipopt integer (20) interpolation options
jpdtn integer product definition template number search options
jpdt integer (100) product definition template values search options
nuv integer number of vector parameter ids
iuv integer (100) vector parameter ids
jpdsb integer (100) kpds search options (map)
jb integer flag for map option
jbk integer flag for map option
lab integer flag for map threshold inequality
ab real map threshold
lam integer flag for mask value
am real mask value
ids integer (255) decimal scaling (-9999 for no change)
ibs integer (255) binary scaling (-9999 for no change)
nbs integer (255) number of bits (-9999 for no change)
lgb integer unit number for grib file map
lxb integer unit number for grib index file map
mb integer dimension of grib field map
cbufb character (mbuf) index buffer map
nlenb integer length of each index record map
nnumb integer number of index records map
mnumb integer number of index records map skipped
lgm integer unit number for grib file merge
lxm integer unit number for grib index file merge
mm integer dimension of grib field merge
lg2 integer unit number for grib file 2
lxx integer flag for verbose output
ks1 integer input record counter
no integer output record counter
iret integer return code
Author
Iredell
Date
96-07-19
Definition at line 821 of file copygb2.F90.
References intgrib2().
Referenced by cpgb().
subroutine copygb2::eusage
Print proper usage to stderr.
Author
Iredell
Date
1996-07-19
Definition at line 535 of file copygb2.F90.
Referenced by copygb2().
subroutine copygb2::intgrib1 ( K1F, integer, dimension(200) KGDS1F, K2F, integer, dimension(200) KGDS2F, MRL, MRO, IV, IP, integer, dimension(20) IPOPT, integer, dimension(200) KGDS1, K1, IB1, logical*1, dimension(k1) L1, real, dimension(k1) F1, real, dimension(k1) G1, integer, dimension(200) KGDS2, K2, IB2, logical*1, dimension(k2) L2, real, dimension(k2) F2, real, dimension(k2) G2, IRET)
Interpolate field.
Parameters
k1f integer regularized input dimension
kgds1f integer (200) regularized input grid parameters
k2f integer regularized output dimension
kgds2f integer (200) regularized output grid parameters
mrl integer dimension of rlat and rlon
mro integer dimension of crot and srot
iv integer vector flag
ip integer interpolation type
ipopt integer (20) interpolation options
kgds1 integer (200) input grid parameters
k1 integer input dimension
ib1 integer input bitmap flag
l1 logical*1 (k1) input bitmap if ib1=1
f1 real (k1) input field
g1 real (k1) input y-component if iv=1
kgds2 integer (200) output grid parameters
k2 integer output dimension
ib2 integer output bitmap flag
l2 logical*1 (k2) output bitmap
f2 real (k2) output field
g2 real (k2) output y-component if iv=1
iret integer return code
Author
Iredell
Date
96-07-19
Definition at line 1332 of file copygb2.F90.
Referenced by intgrib2().
subroutine copygb2::intgrib2 ( IV, IP, integer, dimension(20) IPOPT, NGDT1, integer, dimension(*) KGDT1, IDEFN1, integer, dimension(idefn1) IDEF1, K1, IB1, logical*1, dimension(k1) L1, real, dimension(k1) F1, real, dimension(k1) G1, NGDT2, integer, dimension(*) KGDT2, K2, IB2, logical*1, dimension(k2) L2, real, dimension(k2) F2, real, dimension(k2) G2, IRET)
Interpolate field.
Parameters
iv integer vector flag
ip integer interpolation type
ipopt integer (20) interpolation options
ngdt1 integer (200) input grid definition template number
kgdt1 integer (200) input grid definition template values
idefn1 ???
idef1 ???
k1 integer input dimension
ib1 integer input bitmap flag
l1 logical*1 (k1) input bitmap if ib1=1
f1 real (k1) input field
g1 real (k1) input y-component if iv=1
ngdt2 integer (200) output grid definition template number
kgdt2 integer (200) output grid definition template values
k2 integer output dimension
ib2 integer output bitmap flag
l2 logical*1 (k2) output bitmap
f2 real (k2) output field
g2 real (k2) output y-component if iv=1
iret integer return code
Author
Iredell
Date
96-07-19
Definition at line 1233 of file copygb2.F90.
References intgrib1(), and lengdsf().
Referenced by cpgb1().
function copygb2::lengdsf (integer, dimension(200) KGDS, integer, dimension(200) KGDSF)
Return the length of a filled grid. Given a grid description section (in w3fi63 format), return the grid description section and size of its regularized counterpart. That is, if the input grid is regular, then itself is returned along with its grid size; however if the input grid is only quasi-regular (such as the wafs grids), then its filled regular version is returned along with its filled grid size.
Parameters
kgds integer (200) gds parameters in w3fi63 format
kgdsf integer (200) regular gds parameters in w3fi63 format
Returns
integer size of regularized grid
Author
Iredell
Date
96-07-19
Definition at line 1455 of file copygb2.F90.
Referenced by intgrib2().
function copygb2::numpts (integer, intent(in) IGDTN, integer, dimension(*), intent(in) KGDT)
Return the number of points in a grid. Given a grid definition template number and the grid definition template values, this function will return the number of grid points defined by the specified grid. If the grid template is not recognized, a negative value is returned.
Parameters
igdtn integer grid definition template number
kgdt integer (200) grid definition template values
Returns
integer number of grid points in grid
Author
Gilbert
Date
2005-01-10
Definition at line 1491 of file copygb2.F90.
Referenced by copygb2(), and cpgb().
Author
Generated automatically by Doxygen for copygb2 from the source code.