.TH "/home/ed/NCEPLIBS-grib_util/src/grb2index/grb2index.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "grb2index" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/grb2index/grb2index.f \- WRITE A GRIB2 INDEX FILE\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBgrb2index\fP"
.br
.RI "PROGRAM CREATES AN INDEX FILE FROM A GRIB2 FILE\&. "
.ti -1c
.RI "function \fBncbase\fP (C, N)"
.br
.ti -1c
.RI "subroutine \fBwrgi1h\fP (LUGI, NLEN, NNUM, CGB)"
.br
.in -1c
.SH "Detailed Description"
.PP 
WRITE A GRIB2 INDEX FILE\&. 


.PP
\fBAuthor\fP
.RS 4
GILBERT 
.RE
.PP
\fBDate\fP
.RS 4
2002-01-03 
.RE
.PP

.PP
Definition in file \fBgrb2index\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program grb2index"

.PP
PROGRAM CREATES AN INDEX FILE FROM A GRIB2 FILE\&. THE INDEX FILE SERVES AS A TABLE OF CONTENTS FOR THE GRIB FILE, ENABLING QUICK ACCESS TO THE DATA\&. THE GRIB FILE MUST BE UNBLOCKED, BUT THERE CAN BE A GAP BEFORE THE FIRST GRIB MESSAGE OF AT MOST 32000 BYTES AND GAPS BETWEEN MESSAGES OF AT MOST 4000 BYTES\&. THE TWO FILE NAMES ARE RETRIEVED FROM THE COMMAND LINE ARGUMENTS\&. THE FIRST ARGUMENT IS THE NAME OF THE INPUT GRIB FILE\&. THE SECOND ARGUMENT IS THE NAME OF THE OUTPUT INDEX FILE\&. FOR THIS PROGRAM, ONLY GRIB VERSION 2 CAN BE READ\&. VERSION 1 OF THE INDEX FILE HAS THE FOLLOWING FORMAT: 81-BYTE S\&.LORD HEADER WITH 'GB2IX1' IN COLUMNS 42-47 FOLLOWED BY 81-BYTE HEADER WITH NUMBER OF BYTES TO SKIP BEFORE INDEX RECORDS, TOTAL LENGTH IN BYTES OF THE INDEX RECORDS, NUMBER OF INDEX RECORDS, AND GRIB FILE BASENAME WRITTEN IN FORMAT ('IX1FORM:',3I10,2X,A40)\&. EACH FOLLOWING INDEX RECORD CORRESPONDS TO A FIELD IN A GRIB2 MESSAGE AND HAS THE INTERNAL FORMAT:
.IP "\(bu" 2
BYTE 001 - 004: LENGTH OF INDEX RECORD
.IP "\(bu" 2
BYTE 005 - 008: BYTES TO SKIP IN DATA FILE BEFORE GRIB MESSAGE
.IP "\(bu" 2
BYTE 009 - 012: BYTES TO SKIP IN MESSAGE BEFORE GDS
.IP "\(bu" 2
BYTE 013 - 016: BYTES TO SKIP IN MESSAGE BEFORE PDS
.IP "\(bu" 2
BYTE 017 - 020: BYTES TO SKIP IN MESSAGE BEFORE DRS
.IP "\(bu" 2
BYTE 021 - 024: BYTES TO SKIP IN MESSAGE BEFORE BMS
.IP "\(bu" 2
BYTE 025 - 032: BYTES TOTAL IN THE MESSAGE
.IP "\(bu" 2
BYTE 033 - 033: GRIB VERSION NUMBER ( CURRENTLY 2 )
.IP "\(bu" 2
BYTE 034 - 034: MESSAGE DISCIPLINE
.IP "\(bu" 2
BYTE 035 - 036: FIELD NUMBER WITHIN GRIB2 MESSAGE
.IP "\(bu" 2
BYTE 037 - II: IDENTIFICATION SECTION (IDS)
.IP "\(bu" 2
BYTE II+1- JJ: GRID DEFINITION SECTION (GDS)
.IP "\(bu" 2
BYTE JJ+1- KK: PRODUCT DEFINITION SECTION (PDS)
.IP "\(bu" 2
BYTE KK+1- LL: THE DATA REPRESENTATION SECTION (DRS)
.IP "\(bu" 2
BYTE LL+1-LL+6: FIRST 6 BYTES OF THE BIT MAP SECTION (BMS)
.PP
.PP
PROGRAM HISTORY LOG:
.IP "\(bu" 2
92-11-22 IREDELL
.IP "\(bu" 2
2002-01-03 GILBERT - MODIFIED FROM PROGRAM GRBINDEX TO WORK WITH GRIB2
.IP "\(bu" 2
2005-02-25 GILBERT - Removed buffering option (see baseto)\&.
.IP "\(bu" 2
2012-08-01 VUONG - CHANGED HOSTNAME TO HOSTNAM
.PP
.PP
USAGE: grb2index gribfile indexfile
.PP
INPUT FILE:
.IP "\(bu" 2
gribfile GRIB2 FILE
.PP
.PP
OUTPUT FILE:
.IP "\(bu" 2
indexfile UNBLOCKED INDEX FILE
.PP
.PP
SUBPROGRAMS CALLED:
.IP "\(bu" 2
IARGC COUNT THE COMMAND LINE ARGUMENTS
.IP "\(bu" 2
GETARG GET COMMAND LINE ARGUMENT
.IP "\(bu" 2
WRGI1H WRITE INDEX HEADERS
.IP "\(bu" 2
GETG2IR GET INDEX BUFFER
.IP "\(bu" 2
BAWRITE BYTE-ADDRESSABLE WRITE
.IP "\(bu" 2
ERRMSG WRITE A MESSAGE TO STDERR
.IP "\(bu" 2
ERREXIT EXIT WITH RETURN CODE
.PP
.PP
EXIT STATES:
.IP "\(bu" 2
COND = 0 - SUCCESSFUL RUN
.IP "\(bu" 2
COND = 1 - GRIB MESSAGE NOT FOUND
.IP "\(bu" 2
COND = 2 - INCORRECT ARGUMENTS
.IP "\(bu" 2
COND = 8 - ERROR ACCESSING FILE 
.PP

.PP
Definition at line 66 of file grb2index\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grb2index from the source code\&.
