/home/ed/NCEPLIBS-grib_util/src/grb2index/grb2index.F90
NAME
/home/ed/NCEPLIBS-grib_util/src/grb2index/grb2index.F90 - Write a GRIB2 index file.
SYNOPSIS
Functions/Subroutines
program grb2index
This program creates an index file from a GRIB2 file.
function ncbase (C, N)
Locate basename of a file.
subroutine wrgi1h (LUGI, NLEN, NNUM, CGB)
Write index headers.
Detailed Description
Write a GRIB2 index file.
Author
Iredell
Date
1992-11-22
Definition in file grb2index.F90.
Function/Subroutine Documentation
program grb2index
This program creates an index file from a GRIB2 file.
Returns
0 successful run
1 GRIB message not found
2 incorrect arguments
8 error accessing file
Author
Iredell
Date
1992-11-22
Definition at line 15 of file grb2index.F90.
References wrgi1h().
function ncbase (character, dimension(*) C, N)
Locate basename of a file. This subprogram locates the character number after the last '/' in a character string. For unix filenames, the character number returned marks the beginning of the basename of the file.
Parameters
c character string to search
n integer length of string
Returns
The index of the basename within the string.
Author
Iredell
Date
93-11-22
Definition at line 172 of file grb2index.F90.
Referenced by wrgi1h().
subroutine wrgi1h ( LUGI, NLEN, NNUM, character, dimension(*) CGB)
Write index headers.
Program History Log
Date Programmer Comments 95-10-31 Iredell modularize system calls 2005-02-25 Gilbert et Header bytes 49-54 to blanks. 2012-08-01 Vuong changed hostname to hostnam
Parameters
lugi integer logical unit of output index file
nlen integer total length of index records
nnum integer number of index records
cgb character name of GRIB file
Author
Iredell
Date
93-11-22
Definition at line 111 of file grb2index.F90.
References ncbase().
Referenced by grb2index().
Author
Generated automatically by Doxygen for grb2index from the source code.