/home/ed/NCEPLIBS-grib_util/src/grbindex/grbindex.f
NAME
/home/ed/NCEPLIBS-grib_util/src/grbindex/grbindex.f - Create an index file from a grib file.
SYNOPSIS
Functions/Subroutines
program grbindex
Create an index file from a grib file.
function ncbase (C, N)
Locate basename of a file.
subroutine wrgi1h (LUGI, NLEN, NNUM, CGB)
Write index headers.
Detailed Description
Create an index file from a grib file.
Author
Iredell
Date
1998-09-15
Definition in file grbindex.f.
Function/Subroutine Documentation
program grbindex
Create an index file from a grib file.
Usage
grbindex <GRIB1 file> <index filename>
Returns
0 - successful run
1 - grib message not found
2 - incorrect arguments
8 - error accessing file
Author
Iredell
Date
1998-09-15
Definition at line 17 of file grbindex.f.
References wrgi1h().
function ncbase (character, dimension(*) C, N)
Locate basename of a file. This subprogram locates the character number after the last in a character string. For unix filenames, the character number returned marks the beginning of the basename of the file.
Parameters
C CHARACTER STRING TO SEARCH
N INTEGER LENGTH OF STRING
Returns
The index of the basename within the string.
Author
Iredell
Date
93-11-22
Definition at line 164 of file grbindex.f.
Referenced by wrgi1h().
subroutine wrgi1h ( LUGI, NLEN, NNUM, character, dimension(*) CGB)
Write index headers. This subprogram writes two index headers. Currently, the length of each index record is 152.
Program History Log
Date Programmer Comments 93-11-22 Iredell Initial 95-10-31 Iredell Modularize system calls 2012-07-31 Vuong Changed hostname to hostnam
Parameters
lugi integer logical unit of output index file
nlen integer length of index records
nnum integer number of index records
cgb character name of grib file
Author
Iredell
Date
93-11-22
Definition at line 103 of file grbindex.f.
References ncbase().
Referenced by grbindex().
Author
Generated automatically by Doxygen for grbindex from the source code.