# This is a GitHub actions workflow for the NCEPLIBS-grib_util project.
#
# This workflow builds on MacOS.
#
# Ed Hartnett 1/19/23
name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  MacOS: 
    runs-on: macos-latest
    env:
      FC: gfortran-11
      CC: gcc-11

    steps:
    - name: install-dependencies
      run: |
        brew install libpng

    - name: cache-jasper
      id: cache-jasper
      uses: actions/cache@v3
      with:
        path: ~/jasper
        key: jasper-MacOS-${{ runner.os }}-4.0.0

    - name: checkout-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: jasper-software/jasper
        path: jasper
        ref: version-4.0.0

    - name: build-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      run: |
        cd jasper
        mkdir build-jasper && cd build-jasper
        cmake .. -DCMAKE_INSTALL_PREFIX=~/jasper
        make -j2
        make install

    - name: cache-bacio
      id: cache-bacio
      uses: actions/cache@v3
      with:
        path: ~/bacio
        key: bacio-MacOS-${{ runner.os }}-2.6.0

    - name: checkout-bacio
      if: steps.cache-bacio.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: NOAA-EMC/NCEPLIBS-bacio
        path: bacio
        ref: v2.6.0
    
    - name: build-bacio
      if: steps.cache-bacio.outputs.cache-hit != 'true'
      run: |
        cd bacio
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/bacio
        make -j2
        make install
          
    - name: cache-w3emc
      id: cache-w3emc
      uses: actions/cache@v3
      with:
        path: ~/w3emc
        key: w3emc-MacOS-${{ runner.os }}-2.10.0

    - name: checkout-w3emc
      if: steps.cache-w3emc.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: NOAA-EMC/NCEPLIBS-w3emc
        path: w3emc
        ref: v2.10.0

    - name: build-w3emc
      if: steps.cache-w3emc.outputs.cache-hit != 'true'
      run: |
        cd w3emc
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=~/bacio -DCMAKE_INSTALL_PREFIX=~/w3emc -DBUILD_WITH_BUFR=OFF
        make -j2
        make install
          
    - name: cache-ip
      id: cache-ip
      uses: actions/cache@v3
      with:
        path: ~/ip
        key: ip-MacOS-${{ runner.os }}-5.0.0

    - name: checkout-ip
      if: steps.cache-ip.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: NOAA-EMC/NCEPLIBS-ip
        path: ip
        ref: v5.0.0

    - name: build-ip
      if: steps.cache-ip.outputs.cache-hit != 'true'
      run: |
        cd ip
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/ip
        make -j2
        make install
          
    - name: cache-g2
      id: cache-g2
      uses: actions/cache@v3
      with:
        path: ~/g2
        key: g2-MacOS-${{ runner.os }}-4.0.0-2.6.0-3.4.8-1

    - name: checkout-g2
      if: steps.cache-g2.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: NOAA-EMC/NCEPLIBS-g2
        path: g2
        ref: develop #v3.4.8

    - name: build-g2
      if: steps.cache-g2.outputs.cache-hit != 'true'
      run: |
        cd g2
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/g2 -DCMAKE_PREFIX_PATH="~/bacio;~/jasper" ..
        make -j2
        make install
                 
    - name: checkout-grib_utils
      uses: actions/checkout@v3
      with: 
        path: grib_utils

    - name: build-grib_utils
      run: |
        cd grib_utils
        mkdir build && cd build
        cmake -DCMAKE_PREFIX_PATH="~/bacio;~/jasper;~/ip;~/w3emc;~/g2" ..
        make -j2
        ctest --output-on-failure --rerun-failed --verbose
