/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnv21.f
NAME
/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnv21.f
SYNOPSIS
Functions/Subroutines
subroutine cnv21 (ifl1, ifl2)
This subroutine converts every GRIB2 field in a file to a GRIB1 field.
Detailed Description
. . .
Author
Gilbert
Date
2003-06-11
Definition in file cnv21.f.
Function/Subroutine Documentation
subroutine cnv21 (integer, intent(in) ifl1, integer, intent(in) ifl2)
This subroutine converts every GRIB2 field in a file to a GRIB1 field. If a GRIB2 message contains more than one data field, then each field is saved in individual GRIB1 messages.
PROGRAM HISTORY LOG: 2003-06-11 Gilbert 2008-05-14 Vuong - Add option -m0 No explicit missing values included within data values
USAGE: CALL cnv21(ifl1,ifl2) INPUT ARGUMENT LIST: ifl1 - Fortran unit number of input GRIB2 file ifl2 - Fortran unit number of output GRIB1 file
INPUT FILES: See ifl1
OUTPUT FILES: See ifl2
REMARKS: None
ATTRIBUTES: LANGUAGE: Fortran 90 MACHINE: IBM SP
Definition at line 31 of file cnv21.f.
References gdt2gds(), makepds(), makepdsens(), and putgbexn().
Referenced by cnvgrib().
Author
Generated automatically by Doxygen for cnvgrib from the source code.