/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnvgrib.f
NAME
/home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnvgrib.f
SYNOPSIS
Functions/Subroutines
program cnvgrib
This program converts every GRIB field in a file from.
subroutine usage (iopt)
Detailed Description
Author
Gilbert
Date
2003-06-06
Definition in file cnvgrib.f.
Function/Subroutine Documentation
program cnvgrib
This program converts every GRIB field in a file from.
(1) GRIB1 to GRIB2
(2) GRIB2 to GRIB1
(3) GRIB2 to GRIB2.
PROGRAM HISTORY LOG:
2003-06-06 Gilbert
2008-05-14 Vuong Added the option -m0 (No explicit missing values included within the datavalues, modified the options and help messages
2010-12-02 Vuong Changed Master Table Version Number from 2 to 6. Add option -mastertable_ver_x where x is mater table version 2 to 10
2012-03-29 Vuong Changed Master Table Version Number from 2 to 8.
2013-07-24 Vuong Changed Master Table Version Number from 2 to 11
2016-09-30 Vuong Modified to correct forecast hour beyon F252 when convert from grib2 to grib1. Fixed memory leak and complex packing
2018-07-26 Vuong Checked Time Range for continuous accumulated APCP after F252 when convert from grib2 to grib1
USAGE:
INPUT FILES: UNIT 10 - Input GRIB file
OUTPUT FILES: UNIT 50 - Output GRIB file
LIBRARY: W3LIB - errexit BACIO - baopenr, baopenw, baclose
EXIT STATES: COND = 0 - SUCCESSFUL RUN = 2 - Problem processing command line arguments = 3 - Problem opening input GRIB file = 4 - Problem opening output GRIB file = 5 - Unknown conversion option
REMARKS: LIST CAVEATS, OTHER HELPFUL HINTS OR INFORMATION
Definition at line 46 of file cnvgrib.f.
References cnv12(), cnv21(), and cnv22().
Author
Generated automatically by Doxygen for cnvgrib from the source code.