.TH "/home/ed/NCEPLIBS-grib_util/src/grbindex/grbindex.f" 3 "Tue Dec 14 2021" "Version 1.2.3" "grbindex" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/NCEPLIBS-grib_util/src/grbindex/grbindex.f \- WRITE AN INDEX FILE\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBgrbindex\fP"
.br
.RI "PROGRAM CREATES AN INDEX FILE FROM A GRIB FILE\&. "
.ti -1c
.RI "function \fBncbase\fP (C, N)"
.br
.ti -1c
.RI "subroutine \fBwrgi1h\fP (LUGI, NLEN, NNUM, CGB)"
.br
.in -1c
.SH "Detailed Description"
.PP 
WRITE AN INDEX FILE\&. 


.PP
\fBAuthor\fP
.RS 4
IREDELL 
.RE
.PP
\fBDate\fP
.RS 4
1998-09-15 
.RE
.PP

.PP
Definition in file \fBgrbindex\&.f\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program grbindex"

.PP
PROGRAM CREATES AN INDEX FILE FROM A GRIB FILE\&. THE INDEX FILE SERVES AS A TABLE OF CONTENTS FOR THE GRIB FILE, ENABLING QUICK ACCESS TO THE DATA\&. THE GRIB FILE MUST BE UNBLOCKED, BUT THERE CAN BE A GAP BEFORE THE FIRST GRIB MESSAGE OF AT MOST 32000 BYTES AND GAPS BETWEEN MESSAGES OF AT MOST 4000 BYTES\&. THE TWO FILE NAMES ARE RETRIEVED FROM THE COMMAND LINE ARGUMENTS\&. THE FIRST ARGUMENT IS THE NAME OF THE INPUT GRIB FILE\&. THE SECOND ARGUMENT IS THE NAME OF THE OUTPUT INDEX FILE\&. CURRENTLY, ONLY VERSION 1 OF GRIB CAN BE READ\&. VERSION 1 OF THE INDEX FILE HAS THE FOLLOWING FORMAT: 81-BYTE S\&.LORD HEADER WITH 'GB1IX1' IN COLUMNS 42-47 FOLLOWED BY 81-BYTE HEADER WITH NUMBER OF BYTES TO SKIP BEFORE INDEX RECORDS, NUMBER OF BYTES IN EACH INDEX RECORD, NUMBER OF INDEX RECORDS, AND GRIB FILE BASENAME WRITTEN IN FORMAT ('IX1FORM:',3I10,2X,A40)\&. EACH FOLLOWING INDEX RECORD CORRESPONDS TO A GRIB MESSAGE AND HAS THE INTERNAL FORMAT:
.IP "\(bu" 2
BYTE 001-004: BYTES TO SKIP IN DATA FILE BEFORE GRIB MESSAGE
.IP "\(bu" 2
BYTE 005-008: BYTES TO SKIP IN MESSAGE BEFORE PDS
.IP "\(bu" 2
BYTE 009-012: BYTES TO SKIP IN MESSAGE BEFORE GDS (0 IF NO GDS)
.IP "\(bu" 2
BYTE 013-016: BYTES TO SKIP IN MESSAGE BEFORE BMS (0 IF NO BMS)
.IP "\(bu" 2
BYTE 017-020: BYTES TO SKIP IN MESSAGE BEFORE BDS
.IP "\(bu" 2
BYTE 021-024: BYTES TOTAL IN THE MESSAGE
.IP "\(bu" 2
BYTE 025-025: GRIB VERSION NUMBER
.IP "\(bu" 2
BYTE 026-053: PRODUCT DEFINITION SECTION (PDS)
.IP "\(bu" 2
BYTE 054-095: GRID DEFINITION SECTION (GDS) (OR NULLS)
.IP "\(bu" 2
BYTE 096-101: FIRST PART OF THE BIT MAP SECTION (BMS) (OR NULLS)
.IP "\(bu" 2
BYTE 102-112: FIRST PART OF THE BINARY DATA SECTION (BDS)
.IP "\(bu" 2
BYTE 113-172: (OPTIONAL) BYTES 41-100 OF THE PDS
.IP "\(bu" 2
BYTE 173-184: (OPTIONAL) BYTES 29-40 OF THE PDS
.IP "\(bu" 2
BYTE 185-320: (OPTIONAL) BYTES 43-178 OF THE GDS
.PP
.PP
PROGRAM HISTORY LOG:
.IP "\(bu" 2
92-11-22 IREDELL
.IP "\(bu" 2
94-06-08 EBISUZAKI - ELIMINATE ISHELL CALLS
.IP "\(bu" 2
94-08-26 IREDELL - 40 BYTE PDS EXTENSION
.IP "\(bu" 2
95-10-31 IREDELL - CONSIDERABLY REDUCE I/O
.IP "\(bu" 2
96-10-31 IREDELL - AUGMENTED OPTIONAL DEFINITIONS TO BYTE 320
.IP "\(bu" 2
1999-04-27 GILBERT - Changed CALL EXIT(N) to CALL ERREXIT(N) so that the proper error return value is passed back to the shell\&.
.IP "\(bu" 2
2012-07-31 VUONG - CHANGED HOSTNAME TO HOSTNAM
.PP
.PP
USAGE: grbindex gribfile indexfile
.PP
INPUT FILE:
.IP "\(bu" 2
gribfile UNBLOCKED GRIB FILE
.PP
.PP
OUTPUT FILE:
.IP "\(bu" 2
indexfile UNBLOCKED INDEX FILE
.PP
.PP
SUBPROGRAMS CALLED:
.IP "\(bu" 2
IARGC COUNT THE COMMAND LINE ARGUMENTS
.IP "\(bu" 2
GETARG GET COMMAND LINE ARGUMENT
.IP "\(bu" 2
WRGI1H WRITE INDEX HEADERS
.IP "\(bu" 2
GETGIR GET INDEX BUFFER
.IP "\(bu" 2
BAWRITE BYTE-ADDRESSABLE WRITE
.IP "\(bu" 2
ERRMSG WRITE A MESSAGE TO STDERR
.IP "\(bu" 2
ERREXIT EXIT WITH RETURN CODE
.PP
.PP
EXIT STATES:
.IP "\(bu" 2
COND = 0 - SUCCESSFUL RUN
.IP "\(bu" 2
COND = 1 - GRIB MESSAGE NOT FOUND
.IP "\(bu" 2
COND = 2 - INCORRECT ARGUMENTS
.IP "\(bu" 2
COND = 8 - ERROR ACCESSING FILE 
.PP

.PP
Definition at line 70 of file grbindex\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grbindex from the source code\&.
